### ISSUE TITLE
State Transition Time fehlt, Effekte lassen sich nicht auf Gruppen Anwenden, Feature Request

### ISSUE THREAD

**Issue by Plastikman81** [arteck/ioBroker.zigbee2mqtt#101]
### What happened?

Tradfri IKEA | LED1537R6/LED1739R5

Der State Transition time fehlt leider
Kannst Du diesen mit aufnehmen? Dies bitte auch für Gruppen? So das man die Transition Time auch für Gruppen anpassen kann?
Die Einstellung Devicespezifisch "[Einstellungen (spezifisch)" wird nicht bei der Ansteuerung von Gruppen berücksichtigt. Die Lampen schalten sofort von 1 auf 100%.

Des Weiteren würde ich gerne den State Effect auch auf Gruppen anwenden können.
Ist das möglich?

### Adapter version

2.5.0

**Comment by o0shojo0o** [comment]
Hi, ich habe nun für Leuchtmittel und Gruppen ein `Transition Time Override` hinzugefügt, bitte einmal testen https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/dev_%23101

**Comment by Plastikman81** [comment]
Super gemacht! Funktioniert jetzt. Vielen Dank!
