### ISSUE TITLE
[Device problem]: New device Aqara Cube T1 Pro needs additional mapping

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [arteck/ioBroker.zigbee2mqtt#102]
### Link

not yet listed

### Adapter version

2.5.0

### What is missing or not working

Aqara Cube T1 Pro (Lumi CTP-R01) has a new Scene Mode which has a different behaviour than the Action Mode introduced with its predecessor.
The Scene Mode has two new actions: 
`hold`: activated if user picks up the cube and holds it
`side_up`: activated when the cube is resting on a surface
They are exposed in `action.payload`

Hold already is mapped to ioBroker via an entry in states.js, side_up is not yet mapped and cannot be reacted on in ioB.

The device is not yet officially supported by zigbee2mqtt, but an experimental external converter is available and working. [Issue on github](https://github.com/Koenkk/zigbee2mqtt/issues/15652)
Bottomline: zigbee2mqtt is showing the correct data, the mapping to ioB is incomplete.

Addiotionally I would like to see `payload.action`  to be passed though to ioBroker directly

### Device exposes

```JSON
--->>> fromZ2M -> 0x54ef44100062cf1e states: 
{"payload":{"action":"side_up","battery":100,"current":0,"device_temperature":25,"last_seen":"2023-01-05T13:01:54+00:00","linkquality":255,"operationMode":1,"operation_mode":"scene mode","power":1,"power_outage_count":18,"side":2,"side_up":6,"voltage":3054},"topic":"CubeT1"}

--->>> fromZ2M -> 0x54ef44100062cf1e states: 
{"payload":{"action":"hold","battery":100,"current":0,"device_temperature":25,"last_seen":"2023-01-05T13:01:49+00:00","linkquality":255,"operationMode":1,"operation_mode":"scene mode","power":1,"power_outage_count":18,"side":2,"side_up":6,"voltage":3054},"topic":"CubeT1"}
```

**Comment by o0shojo0o** [comment]
Hi @OstfrieseUnterwegs I need the device exposes because I do not do any mapping but generate the data points from the exposes it is very rarely used the states.js.

But it makes first sin to make certain adjustments if the device is also recorded with the final exposes in the zigbee2mqtt.

**Comment by OstfrieseUnterwegs** [comment]
Understood, thanks.
We'll wait for the device to be included in x2m then.

**Comment by o0shojo0o** [comment]
The new version with the support is now available, can mode that now test whether it now runs?
https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.30.0

**Comment by OstfrieseUnterwegs** [comment]
I can confirm the Cube T1 Pro is now included. Works as expected inside ioBroker
