### ISSUE TITLE
For friendly names that consider description

### ISSUE THREAD

**Issue by pepp86** [arteck/ioBroker.zigbee2mqtt#105]
### What happened?

Name of the device in iobroker doesn't show up, neither the zigbee ID nor the description set in z2m

### What did you expect to happen?

Device description set in z2m should be the device name in iobroker

### Adapter version

2.5.0

**Comment by buanet** [comment]
Can you please provide some more information and maybe some screenshots? 

Name should show up here: 
ioB
![image](https://user-images.githubusercontent.com/16137672/210952966-096686fb-2cad-40fb-ac7f-0bb0af5ff493.png)

Z2M
![image](https://user-images.githubusercontent.com/16137672/210952870-7703715e-c77d-4837-a26a-bce6f164afe3.png)

Description seems not to be included. 

Regards,
André

**Comment by pepp86** [comment]
![image](https://user-images.githubusercontent.com/23097221/210953626-29681249-73c2-4bc2-86fb-2af04eeb8f69.png)

Yep, was expecting the name to show up there, but as you see - nothing. Changed logging to silly now, no errors or any messages regarding names/description.

**Comment by nox309** [comment]
I know the phenomenon, with me here actually always a restart of the adapter was enough, once also the Z2M itself. Have you ever done that?

**Comment by pepp86** [comment]
Yep, in all possible scenarios. Seems that this adapter is not reading any values from z2m.

**Comment by nox309** [comment]
but basically the communication of the adapter works, so if you change something in the ioB then that is also taken active?

If all this works or especially if it does not work, please pull once the current version of git. The version number has not changed, but there are already div. Changes incorporated.

**Comment by pepp86** [comment]
Yep, communication works. It's for now only missing the description/name of the device.

**Comment by nox309** [comment]
okay then please pull the current version from Git

**Comment by pepp86** [comment]
No change - still missing names.

**Comment by o0shojo0o** [comment]
What are your names, for example?

**Comment by pepp86** [comment]
![image](https://user-images.githubusercontent.com/23097221/211006974-b92055e7-71bb-4c49-9ba0-7fe19f8c8e3a.png)
nothing special. Is there any chance to get a debug logging of the adapter to see what happens? From what I see, there is not. Enable silly logging, but only see the iobroker own messages (redis etc.)

**Comment by pepp86** [comment]
To add, I've tested also a device without blanks in the description. Deleted all states and restarted. Nothing.

**Comment by pepp86** [comment]
I get the following log now, when changing a description in z2m:

`
2023-01-06 12:59:31.666  - debug: zigbee2mqtt.0 (240481) Device: bridge/response/device/options not found, queue state in incStatsQueue!
2023-01-06 12:59:40.821  - debug: zigbee2mqtt.0 (240481) Device: bridge/response/device/options not found, queue state in incStatsQueue!
2023-01-06 12:59:41.587  - debug: zigbee2mqtt.0 (240481) Device: 901 not found, queue state in incStatsQueue!
2023-01-06 12:59:41.587  - debug: zigbee2mqtt.0 (240481) Device: bridge/response/device/options not found, queue state in incStatsQueue!
2023-01-06 12:59:41.587  - debug: zigbee2mqtt.0 (240481) Device: bridge/response/device/options not found, queue state in incStatsQueue!
`

**Comment by o0shojo0o** [comment]
You have entered the names in the wrong place!
![image](https://user-images.githubusercontent.com/19333515/211013589-05b4c83c-3ba1-472d-a961-ae96c858fabe.png)  

![image](https://user-images.githubusercontent.com/19333515/211013601-2e48b464-234d-4b0f-9ca9-ed4d5405b850.png)

**Comment by pepp86** [comment]
Yes/No - depends on the point of view. My friendly name always stays with the unique id of the device. Koenkk added the description for that purpose.

**Comment by pepp86** [comment]
Here is the PR which implemented it in z2m
https://github.com/Koenkk/zigbee2mqtt/pull/11493

Now, that we at least found the cause of the issue, are you able to look into the description field and use it, if there is a value?

**Comment by o0shojo0o** [comment]
Ok let's say it differently, for the adapter it is currently the wrong place. 
Since I do not have the description as easy to access as I would need it was chosen this way, whether that still changes or is supplemented I have to look at time times.

~~I make but first this issues to, since that will have solved.~~

~~Create for the description please a new issues .~~

**Comment by o0shojo0o** [comment]
I have looked at that, I think I can implement quite easily I test that right away :)

**Comment by o0shojo0o** [comment]
Please test the dev branch: https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/dev_%23105

**Comment by pepp86** [comment]
Works fine for me. Initial load uses description and updated names also get changed.
