### ISSUE TITLE
[Device problem]: Xiaomi Bewegungsmelder (RTCGQ11LM) and `no_occupancy_since`

### ISSUE THREAD

**Issue by david883** [arteck/ioBroker.zigbee2mqtt#113]
### Link

https://www.zigbee2mqtt.io/devices/RTCGQ11LM.html

### Adapter version

2.6.0

### What is missing or not working

Ich habe mehrere Xiaomi Bewegungsmelder (RTCGQ11LM) und deren Datenpunkte sind unter zigbee2mqtt.0.0x00158d0006f6dad4 angelegt. Soweit alles gut.

Jetzt ist es so das sich im Web Fronted von Zigbee2mqtt bei diesen Bewegungsmeldern weitere Werte unter dem Reiter Spezifische Einstellungen wie z.B. occupancy_timeout und no_occupancy_since einstellen lassen.

Diese Datenpunkte werden aber nicht im IoBroker durch den Adapter angelegt.

### Device exposes

```JSON
--->>> fromZ2M -> 0x00158d0006f6dad4 states: {"payload":{"battery":100,"device_temperature":25,"illuminance":0,"illuminance_lux":0,"last_seen":"2023-01-11T19:09:48+00:00","linkquality":94,"occupancy":false,"power_outage_count":7,"voltage":3005},"topic":"BWM Flur OG"}
```

**Comment by o0shojo0o** [comment]
Ja die werde von mir noch nicht verarbeitet, da ich auch nur diese Bewegungsmelder besitze und die leider bei der Funktion Buggy sind. 
Hier nachzulesen https://github.com/Koenkk/zigbee2mqtt/issues/14032

Den Datenpunkt `occupancy_timeout` werde ich nicht erstellen, da dieser über das Webinterface zu pflegen ist.

**Comment by HannesMC** [comment]
I would like to open this topic again.

Is there no way to make this data point possible in the form of - let's call it experimental? 
The "iobroker.zigbee" adapter could also do this. There the data point was called "no_motion".
