### ISSUE TITLE
[feature request] Re-trigger occupancy datapoint if sent again from device

### ISSUE THREAD

**Issue by pepp86** [arteck/ioBroker.zigbee2mqtt#119]
### What happened?

Hi. Datapoint occupancy is once set to true when movement is detected, after that, no re-triggering of the datapoint happens.

### What did you expect to happen?

In my setup I'm using the motion sensor to switch up the light after certain time of the day or if it's dark outside or whatever, but when movement is not retriggered, my scripts won't notice it.

I would like to suggest to set the true state again if submitted from device. Last change will stay at the original timestamp, only timestamp value will be updated.

Happy to discuss.

### How to reproduce it (minimal and precise)

Use a motion sensor in z2m and see the datapoint in ioBroker.

### Adapter version

2.5.0

**Comment by nox309** [comment]
Hi,
I use exactly the same setup.
Everything works for me. Can you tell me which motion detectors you use?

For me, the ones from Ikea and Xiaomi work fine. I have only adjusted the time in z2m when it should jump back to false.

**Comment by pepp86** [comment]
Yes, might be misunderstanding. If the sensor is true from 13:01 to 13:34 my script doesn't get triggered if there is movement at 13:23 and it's dark outside then, but not at 13:01.

I my own implementation I had always set the occupancy datapoint to true again when sensor sent new data.

Hope you understand? :-)

**Comment by buanet** [comment]
@pepp86 I think hat's more a logic problem with your script.
For me it's correct that the datapoint is only triggered when it changes. Triggering on "last update" seems to be the wrong way... This will produce load to the system by running the script again and again although no state is changed.

What about triggering the illuminance as second trigger? So when this falls below a defined level the script will be triggered and lights will switch on when motion is true too... 

Regards,
André

**Comment by pepp86** [comment]
You're completely right with that approach.

I'm not only triggering light - also doing other stuff based on motion detection. e.g. waking the house if movement in certain areas detected after 5.30am - but maybe there is already movement before and during that moment.

Need to think about other solutions then - because your adapter solve so many issues I had with my own implementation via my script.

**Comment by o0shojo0o** [comment]
One times might consider that I set up a global option that updates the status on every message. 
But you should consider that this can create a lot of unnecessary load on the system.

**Comment by thkn1973** [comment]
I havbe also this problem
with an TuYa IH012-RT01.
[https://www.zigbee2mqtt.io/devices/IH012-RT01.html#tuya-ih012-rt01](url)
it goes to true, but after 30 seconds there is still motion the Datapoint wil not be updatet.
I Use also Fhem and MQTT there it will be updatet all 30 Seconds.

**Comment by o0shojo0o** [comment]
Yes, but this is also intended because the state should not be renewed unnecessarily.
Only when the state changes, it is updated.
I will not change this in any case because it would only bring negative effects for the system performance.

I also do not know why this is needed at this point, unless you have a script not so optimally built ;)

**Comment by thkn1973** [comment]
But all the other motion detectors that run through your adapter update it all the time too.
My scripts run on repeated change and then restart a timeout.

**Comment by o0shojo0o** [comment]
And why don't you start your timeouts when no more motion is detected?

**Comment by thkn1973** [comment]
sprichst du eh auch deutsch oder?
Weil versch. Scripts bereits so sind, und wie gesagt alle anderen BWM hast du es ja auch implementiert?
Warum bei denen und jetzt nicht mehr?

**Comment by o0shojo0o** [comment]
Ja das tue ich :) 

Ich habe es bei keinen BWM so implementiert, es wir von zigbee2mqtt vorgeben ob es ein Event ist und das wird immer neu gesetzt, oder ein normaler State und der wird bei Änderung nur neu gesetzt.

**Comment by thkn1973** [comment]
Ja eben, der BWM selbst macht es ja. 
Nur im Adapter wirds nicht angezeigt.

**Comment by o0shojo0o** [comment]
Mein Adapter kennt die Devices nicht und erstellt diese anhand der Exposes die von Z2M übergeben werden. 
Wenn ich das ändern würde würde alle aber auch alle States andauernd neu gesetzt, und wäre zumindest bei einer  größeren zigbee2mqtt System echt negativ.

**Comment by thkn1973** [comment]
soweit kenn ich mich nicht aus , aber wenn du das so sieht und es so ist, OK.
Dann muss ich halt einige Scripts ändern.

**Comment by pepp86** [comment]
Hi @o0shojo0o . I've created a solution for myself to update occupancy state every time now in ioBroker.
Also added an admin option to switch that function on/off

What do you think? Would you take this into your adapter?
https://github.com/pepp86/ioBroker.zigbee2mqtt

If you like, I can open a Pull Request. It's not much of code.

**Comment by o0shojo0o** [comment]
I will not get to see it until Sunday at the earliest, just that you do not wonder why not come ;)

**Comment by o0shojo0o** [comment]
Ok I have now found some time, basically I find the adaptations you have implemented well. However, I am afraid that there will be more and more desired exceptions. And the options of the adapter will become too complex or too large.

Now I'm thinking about making it more dynamic, but I still don't have a good idea how to do it ;) 

But why don't you post a PR first, so we can continue to "discuss" and collect ideas there.

**Comment by o0shojo0o** [comment]
@pepp86 did you want to submit another PR?
