### ISSUE TITLE
Einbindung der Zigbee2MQTT UI in ioBroker Admin mit Verschlüsselung (HTTPS)

### ISSUE THREAD

**Issue by buanet** [arteck/ioBroker.zigbee2mqtt#12]
**Describe the bug**  
Nutzt man im ioBroker Admin eine verschlüsselte Verbindung über HTTPS lädt der Browser die eingebettete Zigbee2MQTT UI nicht. 

![image](https://user-images.githubusercontent.com/16137672/194357444-866361b9-beb8-445f-8d87-60028798a890.png)

**To Reproduce**  
1. HTTPS im Admin aktivieren
2.  Zigbee2MQTT im Anmin öffnen

**Expected behavior**  
Zigbee2MQTT Admin Oberfläche sollte angezeigt werden. :)

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/16137672/194357912-cafb80ba-1d2b-4acf-9b25-4c1f2648f9fc.png)

**Versions:**  
 - Adapter version: Admin 6.2.22 / Zigbee2MQTT Adapter 0.2.0
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: Linux/ Docker

**Additional context**  
Leider kann man im Zigbee2MQTT von Haus aus (noch) keine Verschlüsselte Verbindung konfigurieren. Einzige Möglichkeit wäre derzeit die Verwendung eines Proxys für die Einbindung. Wäre halt zu prüfen ob die Websocket Verbindung dann noch tut. 
Alternativ könnte man auch eine Proxyverbindung nur für die Admin UI verfügbar machen (Konfigurationsoption in den Adaptereinstellungen). Zumindest bis Zigbee2MQTT HTTPS unterstützt. 

In jedem Fall sollte ein entsprechender Hinweis in die Doku. :)

MfG,
André

**Comment by o0shojo0o** [comment]
Ja das müssen wir uns mal gemeinsam ansehen :)
 
> In jedem Fall sollte ein entsprechender Hinweis in die Doku. :)

@nox309 ;)

**Comment by o0shojo0o** [comment]
Das URL Schema kann nun gewählt werden, allerdings muss man sich noch immer selbst  um ein Proxy oder der gleichen bemühen. 
![image](https://user-images.githubusercontent.com/19333515/194772835-26105408-9aff-4b49-ac0a-b863e4686401.png)
