### ISSUE TITLE
implement last_seen datapoint

### ISSUE THREAD

**Issue by pepp86** [arteck/ioBroker.zigbee2mqtt#131]
### What happened?

Would like to monitor devices by last_seen datapoint

### What did you expect to happen?

Have last_seen datapoint within the device structury

### Adapter version

2.7.0

**Comment by pepp86** [comment]
To add: battery sensors are only marked as offline after 24 or 25 hours - but with motion sensor I would like to see earlier that there is an error.

**Comment by iot4db** [comment]
Hello,
I agree with the wish and would welcome the implementation.

Thanks
Daniel
