### ISSUE TITLE
external mqtt credentials

### ISSUE THREAD

**Issue by Eistee82** [arteck/ioBroker.zigbee2mqtt#148]

**Comment by o0shojo0o** [comment]
Hi, the MQTT connection type was only an experiment and will not be developed further as the websocket connection is superior in this case.

Therefore, please switch to the websocket connection, as the MQTT connection type will be removed in the future.

**Comment by Eistee82** [comment]
I personally switched back to MQTT adapter because the websocket connection is not stable enough for my setup. MQTT works perfect. Bad to hear that you will not support it. Is there a chanse that someone else maintain the MQTT part of this adapter?

**Comment by o0shojo0o** [comment]
Hi @Eistee82, I decided to add the feature because some users seem to have problems with the websocket. 
Can you please test the dev branch?  
https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/external-mqtt-credentials-%23148

**Comment by Eistee82** [comment]
I no longer use this adapter. Im now using the MQTT Adapter with a script wich extends the Datapoints. So I can't test this for now.
