### ISSUE TITLE
Text in devices tap unreadable - ioBroker.zigbee

### ISSUE THREAD

**Issue by OneCreek** [arteck/ioBroker.zigbee2mqtt#152]
### What happened?

Coming from https://github.com/ioBroker/ioBroker.zigbee/issues/1706

More of a nice to have, but maybe it is doable without too much effort.

In some devices, the text shortened Exposes-Information from zigbee2mqtt is not readable and ends with "..." since the text is too long/big. Also hovering over it doesn't help.
![](https://user-images.githubusercontent.com/107502675/225688562-cb9d66b9-a8d9-40d9-992f-881010c83a62.png)

### Adapter version

ioBroker.zigbee.0 v1.8.10

**Comment by nox309** [comment]
Hi,
I think you are wrong here.
Your picture is from the ioBroker Zigbee Adapter. This adapter has nothing to do with the ioBroker Zigbee Adapter. The converter mentioned there is no part of this adapter.

Here you should find the right converter
I think. https://github.com/Koenkk/zigbee2mqtt

**Comment by OneCreek** [comment]
Thanks and Sorry!
