### ISSUE TITLE
Please correct npm maintainers configuration.

### ISSUE THREAD

**Issue by GermanBluefox** [arteck/ioBroker.zigbee2mqtt#183]
## ioBroker adapter checker for npm access

Access right check for adapter zigbee2mqtt returned the following issue:

Bluefox was not found in the collaborators on NPM!.
Please execute in adapter directory: "npm owner add bluefox iobroker.zigbee2mqtt"

Current maintainers are 
    _shojo_ <shojo@dietru.de>

Please fix the above error as soon as possible.
All adapters listed at ioBroker repositories must have 'bluefox' added as maintainer.

Future version updates at the repositories will be suspended until this problem is fixed.

**Comment by o0shojo0o** [comment]
Bluefox has been invited since the first day, but has not accepted the invitation ...  
<img width="1366" alt="image" src="https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/19333515/be930a1d-a483-4664-a4e8-1d2952a55580">

**Comment by mcm1957** [comment]
@GermanBluefox
