### ISSUE TITLE
[Device problem]: after hold button.. send release message

### ISSUE THREAD

**Issue by arteck** [arteck/ioBroker.zigbee2mqtt#189]
### Link

https://www.zigbee2mqtt.io/devices/WXCJKG13LM.html#xiaomi-wxcjkg13lm

### Adapter version

2.7.5

### What is missing or not working

i miss the release button message after press one button

![grafik](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/6681528/852e17d6-1841-4740-b21d-acae6dac59ec)

![grafik](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/6681528/6fb8c624-f8a6-47fa-91be-6baac16cdb3b)

```
2023-06-21 20:47:24MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b805', payload '{"action":"button_1_hold","last_seen":"2023-06-21T18:47:24+00:00","linkquality":76}'
Info 2023-06-21 20:47:25MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c75b805', payload '{"action":"button_1_release","last_seen":"2023-06-21T18:47:26+00:00","linkquality":72}'

```
### Device exposes

```JSON

```

**Comment by o0shojo0o** [comment]
Actually the data point button_1 should remain at hold  `ture` as long as you press it and fall back to `false` on release.
