### ISSUE TITLE
[Device problem]: TuYa ERS-10TZBVK-AA and Hue_Move

### ISSUE THREAD

**Issue by Paalap** [arteck/ioBroker.zigbee2mqtt#223]
### Link

https://www.zigbee2mqtt.io/devices/ERS-10TZBVK-AA.html

### Adapter version

2.10.1

### What is missing or not working

"Hue_Move" is a true/false state and not a number. Is set to true on button hold and is released by "Hue_Stop" state

### Device exposes

```JSON
(Actaion_rate is a constant amount in this case)
{"payload":{"action":"hue_move","action_rate":15,"action_step_size":null,"action_transition_time":null,"battery":89,"brightness":33,"device":{"applicationVersion":67,"dateCode":"","friendlyName":"xxx","hardwareVersion":1,"ieeeAddr":"xxx","manufacturerID":4098,"manufacturerName":"_TZ3000_4fjiwweb","model":"ERS-10TZBVK-AA","networkAddress":52898,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"linkquality":142,"operation_mode":"command","voltage":2900},"topic":"xxx"}

release state:
{"payload":{"action":"hue_stop","action_rate":null,"action_step_size":null,"action_transition_time":null,"battery":89,"brightness":33,"device":{"applicationVersion":67,"dateCode":"","friendlyName":"xxx","hardwareVersion":1,"ieeeAddr":"xxx","manufacturerID":4098,"manufacturerName":"_TZ3000_4fjiwweb","model":"ERS-10TZBVK-AA","networkAddress":52898,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"linkquality":142,"operation_mode":"command","voltage":2900},"topic":"xxx"}
```

**Comment by o0shojo0o** [comment]
According to the Exposes (https://www.zigbee2mqtt.io/devices/ERS-10TZBVK-AA.html#action-enum)
this is not supposed to be a number but an action that is a boolean in ioBroker. 

![image](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/19333515/91b8e088-f6f8-46d5-a2bc-8e7849f14528)

**Comment by Paalap** [comment]
Yes but the adapter is creating a number state...

**Comment by o0shojo0o** [comment]
Ah ok, yes you are right! 
Change in the payload the `"action_rate":15` ?

**Comment by Paalap** [comment]
Does not matter from my point of view, we would only need the state "true" till we get Hue_stop

**Comment by o0shojo0o** [comment]
Here https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/issues/68 it was implemented at that time, probably then incorrectly ...

is then the `Hue_stop` created as a boolean?

**Comment by o0shojo0o** [comment]
Or better can you give me a picture of the object tree of this device?

**Comment by Paalap** [comment]
Yes, Hue_stop is boolean
![image](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/42343574/3fed6b2e-46cd-49f9-a596-a1cd91a26b81)

**Comment by o0shojo0o** [comment]
Can you please test this branch? 
https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/TuYa-ERS-10TZBVK-AA-and-Hue_Move-%23223

**Comment by Paalap** [comment]
nope, somehow it does not work - also not with  
`if (payload.action_rate) {` (instead of action_level)
`  return payload.action_rate;`
`} else {`
`  return undefined;`
`}`

**Comment by o0shojo0o** [comment]
Did you also install the branch I posted?
Where did you get that code snippet?

**Comment by o0shojo0o** [comment]
Otherwise we can meet in the ioBroker Discord.

**Comment by Paalap** [comment]
yes installed it from the branch and tried to adjust it - I'm new to this adapter and trying to understand the code. For now (by deleting the part for hue_move code) it is working for me (not in a nice way as I would like to see hue_move set to true as long as the button is pushed and released by the action hue_stop. But I'll try to adjust the exposes.js for my purpose.

As I'm chnaging my zigbee setup there are also some other topics for me :)

**Comment by o0shojo0o** [comment]
No, since the logic is different from adapter, it must you worked with the two data points that is also so wanted and owed to the Dynamic Generation of States and can now also not be changed so easily because otherwise many users would hunt me :)

**Comment by o0shojo0o** [comment]
I would already merge the fix now. 
This will close the issues here, but if you have any questions, suggestions or even mistakes, feel free to write a new one :)

**Comment by Paalap** [comment]
Sure, just trying how I could do it for my purposes. I do not want to destroy the existing logic ;)

**Comment by o0shojo0o** [comment]
In this dev branch I added the option 'Generate simple 'Move' and 'Stop' states' this should match your expected behavior. https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/IKEA-E2123-(SYMFONISK-gen2)-Volume-hold-%23224

**Comment by Paalap** [comment]
Thank you for your support and this additional option
