### ISSUE TITLE
[Device problem]: IKEA E2123 (SYMFONISK gen2) Volume hold

### ISSUE THREAD

**Issue by Paalap** [arteck/ioBroker.zigbee2mqtt#224]
### Link

https://www.zigbee2mqtt.io/devices/E2123.html

### Adapter version

2.10.1

### What is missing or not working

The states volume_up_hold and volume_down_hold remains on true. There are no release payload for these buttons. Holding the button generates 3-4 payloads each second with the action hold.

### Device exposes

```JSON
{"payload":{"action":"volume_up_hold","battery":null,"device":{"applicationVersion":1,"dateCode":"20230308","friendlyName":"xxx","hardwareVersion":1,"ieeeAddr":"xxx","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","model":"E2123","networkAddress":53549,"powerSource":"Battery","softwareBuildID":"1.0.35","stackVersion":113,"type":"EndDevice","zclVersion":8},"linkquality":163,"update":{"installed_version":16777269,"latest_version":16777269,"state":"idle"},"update_available":null,"voltage":3000},"topic":"xxx"}
```

**Comment by o0shojo0o** [comment]
But the state basically falls back to `false` or?

**Comment by Paalap** [comment]
No it remains forever true 

The routine for the hold buttons is waiting for a release

**Comment by o0shojo0o** [comment]
Oh that is so not wanted :(

**Comment by o0shojo0o** [comment]
Ah right because he finds a release for the other actions ... 
eg. 
`dots_1_short_release, dots_2_short_release, dots_1_long_release, dots_2_long_release`
https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/blob/5963cc510d792b17028e18f27b050d6516f5d5c6/lib/exposes.js#L668-L702

**Comment by o0shojo0o** [comment]
Can you test the dev branch?
https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/IKEA-E2123-(SYMFONISK-gen2)-Volume-hold-%23224

**Comment by Paalap** [comment]
the adapter is crashing:


```
Cannot read properties of undefined (reading 'brightnessMoveOnOff')

TypeError: Cannot read properties of undefined (reading 'brightnessMoveOnOff') at createDeviceFromExposes (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/lib/exposes.js:370:56) at DeviceController.createDeviceDefinitions (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/lib/deviceController.js:30:43) at Zigbee2mqtt.messageParse (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/main.js:169:40) at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/main.js:135:18) at WebSocket.emit (node:events:525:35) at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/node_modules/ws/lib/websocket.js:1184:20) at Receiver.emit (node:events:513:28) at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/node_modules/ws/lib/receiver.js:541:14) at Receiver.getData (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/node_modules/ws/lib/receiver.js:459:17) at Receiver.startLoop (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/node_modules/ws/lib/receiver.js:158:22)

unhandled promise rejection: Cannot read properties of undefined (reading 'brightnessMoveOnOff')

Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

```

**Comment by o0shojo0o** [comment]
That's strange, it doesn't find an option in your adapter configuration and that can't actually happen like that.

![image](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/19333515/58558890-fbe7-4e83-b4d3-2a16aa39f0a9)

Can you please install the branch over again?

**Comment by Paalap** [comment]
ok, after a new installation it is not crashing, but the status remain on true forever

**Comment by o0shojo0o** [comment]
Hmmm... I'm surprised now. I don't know why this still causes problems.

**Comment by Paalap** [comment]
I'll retest it later in the week

**Comment by o0shojo0o** [comment]
So I have now also bought the IKEA E2123 and it behaves with the firmware `1.0.012 (20211214)` 
and the firmware `1.0.32 (20221219)` as expected.

Except for the orphaned states from the faulty exposes to firmware `1.0.012 (20211214)`, where I can't do anything about it because the exposes specify which states to generate.

**Comment by o0shojo0o** [comment]
If you still have problems, please contact me again here in these issues.

**Comment by Paalap** [comment]
Yes it is working good - thank you!
