### ISSUE TITLE
name und desc der States sind vertauscht

### ISSUE THREAD

**Issue by Eistee82** [arteck/ioBroker.zigbee2mqtt#227]

**Comment by o0shojo0o** [comment]
So jetzt bin ich verwirrt da mein Adapter nicht die Funktionalität hat.
Es werden von Adapter keine State Desc  gesetzt!

<img width="1151" alt="image" src="https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/19333515/5559f5e7-dc99-41c7-9531-3078a42d0186">

**Comment by o0shojo0o** [comment]
Kann ich den issues schließen? 
Denn der Adapter macht auf State ebene keine 'Desc'.
