### ISSUE TITLE
Icons bad quality

### ISSUE THREAD

**Issue by Eistee82** [arteck/ioBroker.zigbee2mqtt#235]

**Comment by o0shojo0o** [comment]
This is intentional, as the images in the object are stored as base64, the icons must be small!
eg. 
```
{
  "type": "device",
  "common": {
    "name": "KU.Sensor.Thermostat",
    "statusStates": {
      "onlineId": "zigbee2mqtt.0.0x00158d0001ff8f95.available"
    },
    "desc": "",
    "icon": "data:image/png;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAcABwDASIAAhEBAxEB/8QAGAABAAMBAAAAAAAAAAAAAAAABwQGCAX/xAApEAABAgYABAYDAAAAAAAAAAABAgMABAUGESEHEjEyEyIjQVFycaHB/8QAFgEBAQEAAAAAAAAAAAAAAAAAAQAC/8QAGBEBAQEBAQAAAAAAAAAAAAAAAAECETH/2gAMAwEAAhEDEQA/ANRTjy2W0lpvxFlQSE83L+4Kbzte76pVFTMlWTKoU6FoaCtIHx3iFWd7W/uIyPxUeeTxBuTwcKKJrHnJ0o4x7/EZ1rgt405bTlTkZeVkasEOuqKsPJXnW1AY3+IskG3DKZDlr2ZyqKgqV0T17VQkxqFHnexH3EF93WDbk1V3KjNs1EzNRe9TlWAkE46jHSE+ooCmATnyqChuODWnCWxkduxhSh/YLJfUq1qLl5Ss0elyTT7UtJrXLoS8NkJQrcKEH1t0tibuBqccU6HZYlSAFayQRvO/eEGFP//Z"
  },
  "native": {
    "deviceRemoved": false,
    "groupDevice": false
  },
  "from": "system.adapter.zigbee2mqtt.0",
  "user": "system.user.admin",
  "ts": 1692445068085,
  "_id": "zigbee2mqtt.0.0x00158d0001ff8f95",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

It is also unusual to create issues for an unreleased version.

**Comment by Eistee82** [comment]
Bilder in den Odner zigbee2mqtt.admin laden statt in zigbee2mqtt.0
![image](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/1881217/ca35ddf0-7a17-44ca-a62a-0d2a5bb4587b)
und dann als Datei referenzieren
![image](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/1881217/240850c6-aed7-41cf-aca4-06ce81a59a5e)

**Comment by o0shojo0o** [comment]
Nein, ein Icon mit einen Link hinzuzufügen kann Probleme mit z.B. Lovelace geben, das habe ich alles schon mit den CoreDevs durchgesprochen. 

Und warum willst du eine höherer Auflösung, der Admin gibt die eh nur in 28x28 wieder?!

**Comment by Eistee82** [comment]
Ahja 28x28 icons weil lovelace das nicht kann aber keine gerätenamen für blockly. OK glaub das wars hier für mich. ich mach wieder mein eigenes zigbee2mqtt. ich komm mit deiner Logik nicht klar sorry

**Comment by o0shojo0o** [comment]
Mach das .....
