### ISSUE TITLE
Error: Bei Lidl HG06337 Geräten - Funktion Icons Laden

### ISSUE THREAD

**Issue by A13nka** [arteck/ioBroker.zigbee2mqtt#261]
### What happened?

Sobald die Funktion Icons laden aktiviert ist, entsteht bei Lidl HG06337 Geräten folgender Fehler:

zigbee2mqtt.0 | 2023-10-25 22:04:16.863 | warn | Cannot Fernseher create Device from Exposes!
-- | -- | -- | --

Durch den Fehler lässt sich das Gerät im ioBroker nicht mehr steuern. 

### Adapter version

2.13.3/2.12.0

### Adapter Config Log

igbee2mqtt.0 | 2023-10-25 22:04:16.269 | info | ============================ Zigbee2MQTT Information =============================
-- | -- | -- | --
zigbee2mqtt.0 | 2023-10-25 22:04:16.235 | info | Connect to Zigbee2MQTT over websocket connection.
zigbee2mqtt.0 | 2023-10-25 22:04:14.718 | info | Statring DummyMQTT-Server on IP 0.0.0.0 and Port 1885
zigbee2mqtt.0 | 2023-10-25 22:04:14.638 | info | ==================================================================================
zigbee2mqtt.0 | 2023-10-25 22:04:14.638 | info | \|\| Use Simple Press/Release State: yes
zigbee2mqtt.0 | 2023-10-25 22:04:14.638 | info | \|\| Use Simple Move/Stop State: no
zigbee2mqtt.0 | 2023-10-25 22:04:14.638 | info | \|\| Use Simple Hold/Release State: yes
zigbee2mqtt.0 | 2023-10-25 22:04:14.638 | info | \|\| Use Device Icons: yes
zigbee2mqtt.0 | 2023-10-25 22:04:14.637 | info | \|\| Use Event In Desc: yes
zigbee2mqtt.0 | 2023-10-25 22:04:14.637 | info | \|\| Use BrightnessStep OnOff: yes
zigbee2mqtt.0 | 2023-10-25 22:04:14.637 | info | \|\| Use BrightnessMove OnOff: yes
zigbee2mqtt.0 | 2023-10-25 22:04:14.637 | info | \|\| Use ColorTemperature ColorSync: no
zigbee2mqtt.0 | 2023-10-25 22:04:14.637 | info | \|\| Use Kelvin: no
zigbee2mqtt.0 | 2023-10-25 22:04:14.637 | info | \|\| Proxy Zigbee2MQTT Logs to ioBroker Logs: activated
zigbee2mqtt.0 | 2023-10-25 22:04:14.637 | info | \|\| Zigbee2MQTT Debug Log: deactivated
zigbee2mqtt.0 | 2023-10-25 22:04:14.636 | info | \|\| Zigbee2MQTT Dummy MQTT Port: 1885
zigbee2mqtt.0 | 2023-10-25 22:04:14.636 | info | \|\| Zigbee2MQTT Dummy MQTT IP-Bind: 0.0.0.0
zigbee2mqtt.0 | 2023-10-25 22:04:14.636 | info | \|\| Zigbee2MQTT Websocket Dummy MQTT-Server: activated
zigbee2mqtt.0 | 2023-10-25 22:04:14.636 | info | \|\| Zigbee2MQTT Websocket Auth-Token: unused
zigbee2mqtt.0 | 2023-10-25 22:04:14.635 | info | \|\| Zigbee2MQTT Websocket Port: 8080
zigbee2mqtt.0 | 2023-10-25 22:04:14.635 | info | \|\| Zigbee2MQTT Websocket Server: ******
zigbee2mqtt.0 | 2023-10-25 22:04:14.635 | info | \|\| Zigbee2MQTT Websocket Scheme: ws
zigbee2mqtt.0 | 2023-10-25 22:04:14.635 | info | \|\| Zigbee2MQTT Connection Type: ws
zigbee2mqtt.0 | 2023-10-25 22:04:14.634 | info | \|\| Zigbee2MQTT Frontend Port: 8080
zigbee2mqtt.0 | 2023-10-25 22:04:14.634 | info | \|\| Zigbee2MQTT Frontend Server: ******
zigbee2mqtt.0 | 2023-10-25 22:04:14.634 | info | \|\| Zigbee2MQTT Frontend Scheme: http
zigbee2mqtt.0 | 2023-10-25 22:04:14.633 | info | ================================= Adapter Config =================================
zigbee2mqtt.0 | 2023-10-25 22:04:14.610 | info | starting. Version 2.12.0 in /opt/iobroker/node_modules/iobroker.zigbee2mqtt, node: v18.18.2, js-controller: 5.0.12

**Comment by nox309** [comment]
Hi, 
Also ich habe dasselbe Gerät bei mir, hier herumliegen und habe das eben mal getestet. Bei mir läuft alles ohne Fehler. 
Darf man fragen, wofür du die Icons lädst? 
Ich habe sie bei mir deaktiviert, da ich sie nicht brauche und mir die DB zu sehr aufbläht.
Gruß

**Comment by A13nka** [comment]
Moin,
Ich habe die Icons über die Funktion im Adapter aktiviert, weiteres habe ich nicht getan.
