### ISSUE TITLE
Number wird als String geschrieben

### ISSUE THREAD

**Issue by Eistee82** [arteck/ioBroker.zigbee2mqtt#276]
### What happened?

Meine Heizungsthermostate melden Temperaturen ggf. als 23.0 was in iobroker dann als String geschrieben wird obwohl der Datenpunkt ja ein number ist. Das führt in der weiteren Verarbeitung des Wertes zu Problemen da Berechnungen dann NaN ausgeben. Ein parsefloat bei stats die Number sind kann hier denke ich nicht schaden.

### What did you expect to happen?

Number sollen keine Strings sein

### How to reproduce it (minimal and precise)

Zahlenwert mit ,0 von zigbee2mqtt gerät.

### Adapter version

2.13.3

### Adapter Config Log

Mqtt Verbindung wird benutzt

**Comment by o0shojo0o** [comment]
Der value Type wird von z2m vorgegeben. 
wenn da was nicht passt muss es dort gefixt werden.

**Comment by Eistee82** [comment]
Es hat ja number als Type. Aber bei mqtt und auch bei zigbee2mqtt gibt es ,0 da iobroker aber mit dem Javascript number arbeitet gibt es hier kein ,0 ein Wert von 23,0 ist als number nur 23 es wird aber als String geschrieben da Javascript es ja nicht automatisch in den number Datentypen konvertieren kann

**Comment by o0shojo0o** [comment]
Ich habe das bei mir mal eben nachgesehen, bei mir werden alle Temperaturen mit nachkommerstellen alles als Number im iob gesetzt. 
Auch müsste er bei dir dann im Log immer Warnmeldungen ausgeben das ein String in ein Number Datenpunkt geschrieben wird. 
Ist das der Fall?

**Comment by Eistee82** [comment]
Bekomme ich tatsächlich diese Meldungen:
![image](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/1881217/51fb5e8c-bd21-4761-8d59-8c46ed9f1d6d)

Die Meldung kommt immer wenn ein Wert mit ,0 kommt. Wenn der Wert ,1 oder was anderes hat dann wird er als Zahl in den Number State geschrieben so wie es sein soll.

**Comment by o0shojo0o** [comment]
Teste bitte mal den Branch: https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/Number-wird-als-String-geschrieben-%23276

**Comment by Eistee82** [comment]
Hab Ihn installiert und Log aktiv. Ich werde morgen berichten. Danke

**Comment by Eistee82** [comment]
Das Problem besteht weiterhin
Falls es hilft es handelt sich um diese Heizkörperthermostate: https://www.zigbee2mqtt.io/devices/368308_2010.html#lidl-368308_2010
![image](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/assets/1881217/fef2415a-5490-4c44-9f71-56e378fbadc8)

**Comment by Eistee82** [comment]
.

**Comment by arteck** [comment]
zeigmal das RAW object von dem temperature

**Comment by Eistee82** [comment]
JSON vom MQTT Server
`
{"away_mode":"OFF","away_preset_day":1,"away_preset_days":1,"away_preset_hour":0,"away_preset_minute":0,"away_preset_month":1,"away_preset_temperature":"4.0","away_preset_year":19,"away_setting":null,"binary_one":"OFF","binary_two":"OFF","child_lock":"UNLOCK","color_mode":"xy","comfort_temperature":"22.0","current_heating_setpoint":"10.5","current_heating_setpoint_auto":"21.0","detectwindow_temperature":"15.0","detectwindow_timeminute":0,"device":{"applicationVersion":66,"friendlyName":"bz.Heizung.Fenster","hardwareVersion":1,"ieeeAddr":"0x0c4314fffe619cfd","manufacturerID":4098,"manufacturerName":"_TZE200_chyvmhay","model":"368308_2010","networkAddress":58636,"powerSource":"Battery","type":"EndDevice"},"eco_temperature":"16.0","friday":null,"friday_hour_1":"06","friday_hour_2":"09","friday_hour_3":"17","friday_hour_4":"23","friday_hour_5":"24","friday_hour_6":"24","friday_hour_7":"24","friday_hour_8":"24","friday_minute_1":"00","friday_minute_2":"00","friday_minute_3":"00","friday_minute_4":"00","friday_minute_5":"00","friday_minute_6":"00","friday_minute_7":"00","friday_minute_8":"00","friday_temp_1":"17.0","friday_temp_2":"21.0","friday_temp_3":"17.0","friday_temp_4":"21.0","friday_temp_5":"17.0","friday_temp_6":"21.0","friday_temp_7":"17.0","friday_temp_8":"21.0","friday_temp_9":"17.0","last_seen":"2024-01-06T18:37:40+01:00","linkquality":80,"local_temperature":"20.0","local_temperature_calibration":"-1.2","monday":null,"monday_hour_1":"05","monday_hour_2":"11","monday_hour_3":"24","monday_hour_4":"23","monday_hour_5":"24","monday_hour_6":"24","monday_hour_7":"24","monday_hour_8":"24","monday_minute_1":"00","monday_minute_2":"00","monday_minute_3":"00","monday_minute_4":"00","monday_minute_5":"00","monday_minute_6":"00","monday_minute_7":"00","monday_minute_8":"00","monday_temp_1":"16.0","monday_temp_2":"22.0","monday_temp_3":"16.0","monday_temp_4":"21.0","monday_temp_5":"17.0","monday_temp_6":"21.0","monday_temp_7":"17.0","monday_temp_8":"21.0","monday_temp_9":"17.0","preset":"manual","saturday":null,"saturday_hour_1":"06","saturday_hour_2":"09","saturday_hour_3":"17","saturday_hour_4":"23","saturday_hour_5":"24","saturday_hour_6":"24","saturday_hour_7":"24","saturday_hour_8":"24","saturday_minute_1":"00","saturday_minute_2":"00","saturday_minute_3":"00","saturday_minute_4":"00","saturday_minute_5":"00","saturday_minute_6":"00","saturday_minute_7":"00","saturday_minute_8":"00","saturday_temp_1":"17.0","saturday_temp_2":"21.0","saturday_temp_3":"17.0","saturday_temp_4":"21.0","saturday_temp_5":"17.0","saturday_temp_6":"21.0","saturday_temp_7":"17.0","saturday_temp_8":"21.0","saturday_temp_9":"17.0","sunday":null,"sunday_hour_1":"06","sunday_hour_2":"09","sunday_hour_3":"17","sunday_hour_4":"23","sunday_hour_5":"24","sunday_hour_6":"24","sunday_hour_7":"24","sunday_hour_8":"24","sunday_minute_1":"00","sunday_minute_2":"00","sunday_minute_3":"00","sunday_minute_4":"00","sunday_minute_5":"00","sunday_minute_6":"00","sunday_minute_7":"00","sunday_minute_8":"00","sunday_temp_1":"17.0","sunday_temp_2":"21.0","sunday_temp_3":"17.0","sunday_temp_4":"21.0","sunday_temp_5":"17.0","sunday_temp_6":"21.0","sunday_temp_7":"17.0","sunday_temp_8":"21.0","sunday_temp_9":"17.0","system_mode":"heat","thursday":null,"thursday_hour_1":"06","thursday_hour_2":"09","thursday_hour_3":"17","thursday_hour_4":"23","thursday_hour_5":"24","thursday_hour_6":"24","thursday_hour_7":"24","thursday_hour_8":"24","thursday_minute_1":"00","thursday_minute_2":"00","thursday_minute_3":"00","thursday_minute_4":"00","thursday_minute_5":"00","thursday_minute_6":"00","thursday_minute_7":"00","thursday_minute_8":"00","thursday_temp_1":"17.0","thursday_temp_2":"21.0","thursday_temp_3":"17.0","thursday_temp_4":"21.0","thursday_temp_5":"17.0","thursday_temp_6":"21.0","thursday_temp_7":"17.0","thursday_temp_8":"21.0","thursday_temp_9":"17.0","tuesday":null,"tuesday_hour_1":"06","tuesday_hour_2":"09","tuesday_hour_3":"17","tuesday_hour_4":"23","tuesday_hour_5":"24","tuesday_hour_6":"24","tuesday_hour_7":"24","tuesday_hour_8":"24","tuesday_minute_1":"00","tuesday_minute_2":"00","tuesday_minute_3":"00","tuesday_minute_4":"00","tuesday_minute_5":"00","tuesday_minute_6":"00","tuesday_minute_7":"00","tuesday_minute_8":"00","tuesday_temp_1":"17.0","tuesday_temp_2":"21.0","tuesday_temp_3":"17.0","tuesday_temp_4":"21.0","tuesday_temp_5":"17.0","tuesday_temp_6":"21.0","tuesday_temp_7":"17.0","tuesday_temp_8":"21.0","tuesday_temp_9":"17.0","voltage":1180,"wednesday":null,"wednesday_hour_1":"06","wednesday_hour_2":"09","wednesday_hour_3":"17","wednesday_hour_4":"23","wednesday_hour_5":"24","wednesday_hour_6":"24","wednesday_hour_7":"24","wednesday_hour_8":"24","wednesday_minute_1":"00","wednesday_minute_2":"00","wednesday_minute_3":"00","wednesday_minute_4":"00","wednesday_minute_5":"00","wednesday_minute_6":"00","wednesday_minute_7":"00","wednesday_minute_8":"00","wednesday_temp_1":"17.0","wednesday_temp_2":"21.0","wednesday_temp_3":"17.0","wednesday_temp_4":"21.0","wednesday_temp_5":"17.0","wednesday_temp_6":"21.0","wednesday_temp_7":"17.0","wednesday_temp_8":"21.0","wednesday_temp_9":"17.0"}
`

iobroker Objekt
`
{
  "type": "state",
  "common": {
    "id": "local_temperature",
    "name": "Local Temperature",
    "role": "value.temperature",
    "write": false,
    "read": true,
    "type": "number",
    "def": 0,
    "unit": "°C",
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "storageType": "Number",
        "aliasId": "",
        "debounceTime": 100,
        "blockTime": 100,
        "changesOnly": false,
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "ignoreBelowNumber": "",
        "disableSkippedValueLogging": false,
        "enableDebugLogs": false,
        "debounce": 1000
      }
    }
  },
  "native": {},
  "_id": "zigbee2mqtt.0.0x0c4314fffe63a044.local_temperature",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.zigbee2mqtt.0",
  "user": "system.user.admin",
  "ts": 1704282136181
}
`

**Comment by arteck** [comment]
![grafik](https://github.com/arteck/ioBroker.zigbee2mqtt/assets/6681528/c63220c9-0d8b-45f2-b43b-b3d863a29d30)

#kann ich nicht nachvollziehen.. bei glatten Zahlen in der local_temperature erhalte ich keine Meldung

hier sogar mit callibration wie bei dir
![grafik](https://github.com/arteck/ioBroker.zigbee2mqtt/assets/6681528/89d28e56-df2c-4fd0-817c-2047f7459c41)

ansonsten lösche mal das object (nicht das Gerät im z2m, nur das object im iobroker)
![grafik](https://github.com/arteck/ioBroker.zigbee2mqtt/assets/6681528/e4ca76bd-299f-4dc5-9a7b-e8db1bbf4005)

und starte den adapter neu .. sollte dann neu angelegt werden.. kein plan was da schief läuft

**Comment by Eistee82** [comment]
Da läuft schief das zigbee2mqtt im JSON die local_temperature als String sendet ("local_temperature":"20.0") und dann der zigbee2mqtt iobroker Adapter den String ("20.0") in ein Number Datenpunkt schreibt. Das würde nicht passieren wenn man da ein parseFloat() verwendet.

**Comment by arteck** [comment]
dann stell PR..du siehst das es bei mir funktioniert

**Comment by Eistee82** [comment]
Das Problem besteht weiterhin

**Comment by Eistee82** [comment]
Das Problem besteht weiterhin

**Comment by Eistee82** [comment]
Das Problem besteht weiterhin

**Comment by arteck** [comment]
ich mach zu hier... da du nich in der lage bist ein PR zu stellen obwohl das Problem NUR bei DIR auftrifft...
