### ISSUE TITLE
Geräte wieder offline nach einer bestimmten Zeit (siehe #255)

### ISSUE THREAD

**Issue by Tschaeeens** [arteck/ioBroker.zigbee2mqtt#279]
### What happened?

Seit dem Update auf 2.13.4 und dem zigbee2mqtt update auf 1.34.0 werden die Geräte nach einer bestimmten Zeit wieder als offline angezeigt. Ein Neustart des Adapters zeigt die Geräte wieder als online. 
Getestet sowohl mit websocket als auch mit Externer MQTT Server. 

### How to reproduce it (minimal and precise)

Nach Durchsicht der Logs könnte es möglich sein, dass die Geräte immer dann als offline angezeigt werden, wenn ein Gerät sich selbst announced und anschließend wieder online geht. Ansonsten habe ich nichts auffälliges im Log. 

### Adapter version

2.13.4

### Log

ich werde jetzt mal zigbee2mqtt in der Datei loggen. Vielleicht erkenne ich das Problem.

**Comment by arteck** [comment]
kann ich nicht bestätigen..
sind die Geräte vielleicht nur offline markiert wenn du Admin aufmachst..  und direkt in den Objectbaum schaust...
das dauert bissel bis Admin diese richtig markeirt hat 
was steht i den einzelnen Zuständen
![grafik](https://github.com/arteck/ioBroker.zigbee2mqtt/assets/6681528/0fbfc7d7-b277-451d-aa00-41a19ade0e9f)

**Comment by MarkSau** [comment]
Ich habe das tatsächlich auch..heute schon zweimal.. 
Die Objekte werden als Offline im Adapter angezeigt. Im zigbee2mqtt selbst sind sie online und zeigen auch dort nichts im Log.
Es scheint, als ob der Adapter die Verbindung zum zigbee2mqtt verliert.
Nach einem Neustart der iob Instanz ist erstmal alles wieder gut.

**Comment by Tschaeeens** [comment]
Ich habe jetzt mal einiges probiert. Also bei mir zeigt es die Geräte definitiv als offline auch in der Objektansicht an. Das Gerät lässt sich aber weiterhin schalten. Ich habe sowohl mit websocket als auch externen mqtt die Tests durchgeführt. Ich konnte einiges nachstellen. Falls sich ein Gerät announced und wieder neu connected, dann verliert der Adapter nur bei available die Verbindung. Lasst seen wird ebenfalls nicht mehr aktualisiert. Bei mir waren einige batteriebetriebenen Ikea Schalter dabei. Diese hatten alle nur noch wenig Saft. Nachdem ich die Batterien bei fast allen getauscht habe, wurde die Problematik besser. Aktuell habe ich mir in ioBroker ein Skript geschrieben, welches den available Status prüft und wenn mehr als 5 Geräte offline gehen starte ich den Adapter automatisch neu. Danach geht es wieder. Was komisch ist, falls ein batteriebetriebenes Gerät aussteigt, gehen auch die festverbauten Steckdosen offline. Ich habe keinerlei Geräte von Ledvance oder Osram vorhanden. 
Vielleicht hilft dies. Schon mal besten Dank für die Hilfe!

**Comment by DominikReber** [comment]
Hab ein ähnliches Problem seit heute.
Nach einem Neustart sind alle Geräte grün, innerhalb 1-5 minuten verlieren aber alle die Verbindung.
in Zigbee2MQTT sind sie aber weiterhin normal verfügbar.

**Comment by DominikReber** [comment]
Ich muss mich korrigieren, es tritt nur in Verbindung mit einem Gerät auf (Heiman WarningDevice-EF-3.0). Wenn ich einen Befehl an den sende, stürzt der ganze Adapter ab. (Mache einen eigenen Thread auf dafür)

**Comment by DominikReber** [comment]
Aktuell werden sie auch alle als offline markiert, wenn ich ein neues Gerät anlerne. 
Fehlermeldung sehe ich nirgends. In Zigbee2MQTT ist alles aber weiterhin online und - deshalb halb so wild - die Werte werden korrekt über den Adapter empfangen.

Nehme an, dies wird ausgelöst und daher alles als offline angzeigt:

            wsClient.on('close', async () => {
                this.setStateChanged('info.connection', false, true);
                await statesController.setAllAvailableToFalse();
                deviceCache = [];
                groupCache = [];
            });

**Comment by MarkSau** [comment]
Hi,
ich möchte da Thema noch mal hoch holen, da es bei mir etwas nervt. Ich nutze den Device_Watcher dapter, der mir Geräte meldet, die Offline gegangen sind.  Klar könnte ich Zigbee davon ausnehmen, aber das ist ja nicht Sinn der Sache.
Wäre also schön, wenn das bald gelöst würde..
Danke

**Comment by arteck** [comment]
wie soll ich den Fehler beheben wenn keine LOGs geliefert werden ..
mit einer Meldung es läuft nicht ist mir nicht geholfen..

meine Geräte sind IMMER Online.. 
also was ist den bei euch so besonders.. 

zeigtmal die Einstellungen..vielleicht kriegen wir so ein konsens

**Comment by cracyfloyd** [comment]
Bei mir ist das gleiche Problem mit allen Geräten. Ich habe zig Xiaomi Bewegungsmelder, Fensterkontakte und Lichter von Philips und Ikea. Alle werden in dem IOBroker Adapter nach ein paar Stunden  als unavailable angezeigt. In der Zigbee2mqtt Software sind sie aber alle als available markiert.  Starte ich den IOBroker Zigbee2mqtt Adapter neu werden wieder alle als available gekennzeichnet. 
Ich habe einen Docker Mosquito Container und einen Zigbee2mqtt  Docker Container am laufen. Auf diesen greift der zigbee2mqtt IObroker Adapter zu.

<img width="1029" alt="Bildschirmfoto 2024-02-25 um 10 13 28" src="https://github.com/arteck/ioBroker.zigbee2mqtt/assets/57620791/36efa94c-992e-451b-9488-14c491ef6241">
<img width="920" alt="Bildschirmfoto 2024-02-25 um 10 11 57" src="https://github.com/arteck/ioBroker.zigbee2mqtt/assets/57620791/9c690c2f-d01f-4349-821a-d9bd8a8cd332">

**Comment by cracyfloyd** [comment]
Nach ein paar Stunden Betrieb des Adapters wieder das gleiche.

<img width="1111" alt="Bildschirmfoto 2024-02-27 um 21 45 05" src="https://github.com/arteck/ioBroker.zigbee2mqtt/assets/57620791/4fcd4632-e0cd-4b3e-97f0-3b977beced34">

<img width="833" alt="Bildschirmfoto 2024-02-27 um 21 45 32" src="https://github.com/arteck/ioBroker.zigbee2mqtt/assets/57620791/42284c26-914d-4889-b4ba-1061df1f34b2">

Nach Neustart des Adapters sind dann wieder alle available.

<img width="863" alt="Bildschirmfoto 2024-02-27 um 21 49 52" src="https://github.com/arteck/ioBroker.zigbee2mqtt/assets/57620791/b82bf29a-460a-43c9-a2b8-49c2e690929c">

**Comment by copystring** [comment]
Ich hatte das ebenfalls vor Ewigkeiten. Dazu gibt es auch entsprechendes Issue. Sind nie wirklich dahinter gekommen, warum es nicht läuft. Das Problem war damals websocket. Nach dem Wechsel zu mqtt trat es nie wieder auf.

https://github.com/arteck/ioBroker.zigbee2mqtt/issues/87

**Comment by cracyfloyd** [comment]
> Ich hatte das ebenfalls vor Ewigkeiten. Dazu gibt es auch entsprechendes Issue. Sind nie wirklich dahinter gekommen, warum es nicht läuft. Das Problem war damals websocket. Nach dem Wechsel zu mqtt trat es nie wieder auf.
> 
> #87

Danke für die Info. Leider ist das Problem bei mir nicht websocket da ich über MQTT kommuniziere. Vielleicht ist es ja doch an irgendeiner Stelle eine Einstellung. Warten wir mal ab.

**Comment by MMeinhardt1** [comment]
Hi, gibt es zu dem hier genannten Phänomen bzw. Problem irgendwelche Erkenntnisse? Ich habe das Problem auch schon eine ganze Weile immer wieder mal. 

Danke und einen guten Rutsch an alle.
