### ISSUE TITLE
HEIMAN WarningDevice-EF-3.0 - settings a value crashes whole adapter

### ISSUE THREAD

**Issue by DominikReber** [arteck/ioBroker.zigbee2mqtt#304]
### What happened?

When using the smart siren/router HEIMAN WarningDevice-EF-3.0, whenever I set a value (e.g. mode to "burglar"), the whole adapter crashes - all values go to orange/not connected.
Still, everything is working correct in Zigbee2MQTT itself!

### What did you expect to happen?

The value I changed is not send to the alarm device - and it does crash the whole adapter / all device go offline in the adapter.
Still, everything is working correct in Zigbee2MQTT itself!
I can change values there directly! So it has to be a bug in the adapter. 
Adapter then restarts automatically and sometimes it is then working again (for all other devices) and sometimes I have to reinstall the adapter...

### How to reproduce it (minimal and precise)

Set any value will crash the adapter. 

### Adapter version

2.3.4

### Adapter Config Log

zigbee2mqtt.0 | 2024-01-17 08:52:28.916 | info | ==================================================================================
-- | -- | -- | --
zigbee2mqtt.0 | 2024-01-17 08:52:28.916 | info | \|\| Network panid 1470 channel: 11 ext_pan_id: 0
zigbee2mqtt.0 | 2024-01-17 08:52:28.916 | info | \|\| Coordinator type: EZSP v12 Version: 7.3.1.0 build 176 Serial: /dev/ttyACM0
zigbee2mqtt.0 | 2024-01-17 08:52:28.916 | info | \|\| Zigbee2MQTT Version: 1.35.1
zigbee2mqtt.0 | 2024-01-17 08:52:28.915 | info | ============================ Zigbee2MQTT Information =============================
zigbee2mqtt.0 | 2024-01-17 08:52:28.885 | info | Connect to Zigbee2MQTT over websocket connection.
zigbee2mqtt.0 | 2024-01-17 08:52:28.823 | info | ==================================================================================
zigbee2mqtt.0 | 2024-01-17 08:52:28.823 | info | \|\| Coordinator Check Cron : 0 3 * * *
zigbee2mqtt.0 | 2024-01-17 08:52:28.823 | info | \|\| Coordinator Check Loglevel: info
zigbee2mqtt.0 | 2024-01-17 08:52:28.822 | info | \|\| Use Automatic Coordinator Check: no
zigbee2mqtt.0 | 2024-01-17 08:52:28.822 | info | \|\| Use Simple Press/Release State: no
zigbee2mqtt.0 | 2024-01-17 08:52:28.822 | info | \|\| Use Simple Move/Stop State: no
zigbee2mqtt.0 | 2024-01-17 08:52:28.821 | info | \|\| Use Simple Hold/Release State: yes
zigbee2mqtt.0 | 2024-01-17 08:52:28.821 | info | \|\| Use Device Icons: yes
zigbee2mqtt.0 | 2024-01-17 08:52:28.821 | info | \|\| Use Event In Desc: yes
zigbee2mqtt.0 | 2024-01-17 08:52:28.820 | info | \|\| Use BrightnessStep OnOff: no
zigbee2mqtt.0 | 2024-01-17 08:52:28.820 | info | \|\| Use BrightnessMove OnOff: no
zigbee2mqtt.0 | 2024-01-17 08:52:28.820 | info | \|\| Use ColorTemperature ColorSync: no
zigbee2mqtt.0 | 2024-01-17 08:52:28.819 | info | \|\| Use Kelvin: no
zigbee2mqtt.0 | 2024-01-17 08:52:28.819 | info | \|\| Proxy Zigbee2MQTT Logs to ioBroker Logs: activated
zigbee2mqtt.0 | 2024-01-17 08:52:28.818 | info | \|\| Zigbee2MQTT Debug Log: deactivated
zigbee2mqtt.0 | 2024-01-17 08:52:28.817 | info | \|\| Zigbee2MQTT Websocket Dummy MQTT-Server: deactivated
zigbee2mqtt.0 | 2024-01-17 08:52:28.817 | info | \|\| Zigbee2MQTT Websocket Auth-Token: unused
zigbee2mqtt.0 | 2024-01-17 08:52:28.816 | info | \|\| Zigbee2MQTT Websocket Port: 8080
zigbee2mqtt.0 | 2024-01-17 08:52:28.816 | info | \|\| Zigbee2MQTT Websocket Server: 192.168.1.11
zigbee2mqtt.0 | 2024-01-17 08:52:28.815 | info | \|\| Zigbee2MQTT Websocket Scheme: ws
zigbee2mqtt.0 | 2024-01-17 08:52:28.815 | info | \|\| Zigbee2MQTT Connection Type: ws
zigbee2mqtt.0 | 2024-01-17 08:52:28.814 | info | \|\| Zigbee2MQTT Frontend Port: 8080
zigbee2mqtt.0 | 2024-01-17 08:52:28.813 | info | \|\| Zigbee2MQTT Frontend Server: 192.168.1.11
zigbee2mqtt.0 | 2024-01-17 08:52:28.812 | info | \|\| Zigbee2MQTT Frontend Scheme: http
zigbee2mqtt.0 | 2024-01-17 08:52:28.811 | info | ================================= Adapter Config =================================
zigbee2mqtt.0 | 2024-01-17 08:52:28.779 | info | starting. Version 2.13.4 in /opt/iobroker/node_modules/iobroker.zigbee2mqtt, node: v18.16.1, js-controller: 5.0.16
zigbee2mqtt.0 | 2024-01-17 08:51:55.155 | warn | Cannot 2 Lia/Noemi Temperatur create Device from Exposes!
zigbee2mqtt.0 | 2024-01-17 08:51:55.152 | error | Cannot check file existence of "cfg.f.zigbee2mqtt.0$%$WSDCGQ11LM.jpg$%$data": Connection is closed.
zigbee2mqtt.0 | 2024-01-17 08:51:54.628 | info | terminating
zigbee2mqtt.0 | 2024-01-17 08:51:54.443 | info | Connect to Zigbee2MQTT over websocket connection.
zigbee2mqtt.0 | 2024-01-17 08:51:54.419 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee2mqtt.0 | 2024-01-17 08:51:53.432 | warn | Start try again in 1 seconds...
zigbee2mqtt.0 | 2024-01-17 08:51:53.213 | error | Cannot set properties of undefined (setting 'mode')
zigbee2mqtt.0 | 2024-01-17 08:51:53.212 | error | TypeError: Cannot set properties of undefined (setting 'mode') at state.setter (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/lib/exposes.js:1093:52) at Z2mController.createZ2MMessage (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/lib/z2mController.js:35:36) at Zigbee2mqtt.onStateChange (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/main.js:336:49) at Zigbee2mqtt.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8506:53) at process.processImmediate (node:internal/timers:476:21)
zigbee2mqtt.0 | 2024-01-17 08:51:53.210 | error | unhandled promise rejection: Cannot set properties of undefined (setting 'mode')
zigbee2mqtt.0 | 2024-01-17 08:51:53.209 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by arteck** [comment]
check now GIT version

**Comment by DominikReber** [comment]
Installed GIT Version, still same error



zigbee2mqtt.1 | 2024-01-26 12:21:36.467 | error | TypeError: Cannot set properties of undefined (setting 'mode') at state.setter (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/lib/exposes.js:1120:54) at Z2mController.createZ2MMessage (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/lib/z2mController.js:35:36) at Zigbee2mqtt.onStateChange (/opt/iobroker/node_modules/iobroker.zigbee2mqtt/main.js:336:49) at Zigbee2mqtt.emit (node:events:517:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8516:53) at process.processImmediate (node:internal/timers:476:21)
-- | -- | -- | --
zigbee2mqtt.1 | 2024-01-26 12:21:36.464 | error | unhandled promise rejection: Cannot set properties of undefined (setting 'mode')
zigbee2mqtt.1 | 2024-01-26 12:21:36.463 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by Eistee82** [comment]
See #268
