### ISSUE TITLE
Loglevel ändern

### ISSUE THREAD

**Issue by mpl1337** [arteck/ioBroker.zigbee2mqtt#308]
### What happened?

Zigbee Teilnehmer nicht erreichbar, Error im Log. 

Wäre es möglich diese Meldung als "Info" einzustufen oder einen Schalter zum deaktivieren der Meldung vorzusehen?

Ich habe etliche Paulmann leuchten, die weigern sich einfach am Mesh teilzunehmen und sprechen wohl nur mit dem  Koordinator 

Aufgrund der ständigen Abbrüche füllt sich mein log. 

### What did you expect to happen?

Warn/Info im Log

### How to reproduce it (minimal and precise)

Zigbee teilnehmer abschalten

### Adapter version

2.13.4

### Adapter Config Log

<html>
<body>

zigbee2mqtt.0 | 2024-01-20 23:20:23.261 | error | Publish 'set' 'state' to 'Beet 2' failed: 'Error: Command 0x00158d000416c1e5/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 27411 - 1 - 23 - 6 - 11 after 10000ms)'
-- | -- | -- | --
zigbee2mqtt.0 | 2024-01-20 23:20:18.709 | error | Publish 'set' 'state' to 'Beet 6' failed: 'Error: Command 0x00158d0006b3f166/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
zigbee2mqtt.0 | 2024-01-20 23:20:10.160 | error | Publish 'set' 'state' to 'Hinterhaus 1' failed: 'Error: Command 0x00158d000581710d/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":35634,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
zigbee2mqtt.0 | 2024-01-20 23:20:10.142 | error | Publish 'set' 'state' to 'Beet 4' failed: 'Error: Command 0x00158d000400e524/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":26606,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
zigbee2mqtt.0 | 2024-01-20 23:20:10.066 | error | Publish 'set' 'state' to 'Hinterhaus 2' failed: 'Error: Command 0x00158d000577ed85/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":19921,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'

</body>
</html>

### Log

`
zigbee2mqtt.0 | 2024-01-20 23:20:43.744 | error | Failed to execute LQI for 'Beet 6'
-- | -- | -- | --
zigbee2mqtt.0 | 2024-01-20 23:20:23.261 | error | Publish 'set' 'state' to 'Beet 2' failed: 'Error: Command 0x00158d000416c1e5/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 27411 - 1 - 23 - 6 - 11 after 10000ms)'
zigbee2mqtt.0 | 2024-01-20 23:20:18.709 | error | Publish 'set' 'state' to 'Beet 6' failed: 'Error: Command 0x00158d0006b3f166/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
zigbee2mqtt.0 | 2024-01-20 23:20:10.160 | error | Publish 'set' 'state' to 'Hinterhaus 1' failed: 'Error: Command 0x00158d000581710d/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":35634,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
zigbee2mqtt.0 | 2024-01-20 23:20:10.142 | error | Publish 'set' 'state' to 'Beet 4' failed: 'Error: Command 0x00158d000400e524/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":26606,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
zigbee2mqtt.0 | 2024-01-20 23:20:10.066 | error | Publish 'set' 'state' to 'Hinterhaus 2' failed: 'Error: Command 0x00158d000577ed85/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":19921,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
zigbee2mqtt.0 | 2024-01-20 23:20:00.011 | error | Failed to execute LQI for 'Beet 2'
`

**Comment by arteck** [comment]
es liegt an der coodinator Firmware.. da wird schon dran gearbeitet.. geduld

**Comment by mpl1337** [comment]
wo gibt es mehr infos dazu?

**Comment by arteck** [comment]
https://github.com/Koenkk/Z-Stack-firmware/discussions/483
