### ISSUE TITLE
[FR] Switch ID and Name

### ISSUE THREAD

**Issue by Sineos** [arteck/ioBroker.zigbee2mqtt#347]
### What happened?

Just recently I replaced a handful of devices and as a consequence had to rework all logic that relied on these devices due to a change in the IEEE address.

### What did you expect to happen?

I'd like to ask for an option to switch ID (IEEE address) and the device name, so that the data-point contains the device name instead of the IEEE address.

In my view this has some advantages:
* Devices with the same end-points can easily be replaced by a different model with the same end-points
* The device name is easier to follow inside some logic (scripts, Node Red etc)
* It aligns with the zigbee2mqtt logic as it also uses the "friendly name" for its messages

To avoid breaking existing logics, this could be a setting that defaults to the current naming scheme.

Thanks for this incredibly useful adapter and thanks in advance for giving this proposal some thoughts.

### How to reproduce it (minimal and precise)

n/a

### Adapter version

v2.13.6

### Adapter Config Log

n/a

### Log

n/a

**Comment by arteck** [comment]
this adapter is like zigbee adapter.. with same logic.. and NO we dont switch the ID to name.. 
its maybe for you project better but not for all.. sry
