### ISSUE TITLE
In groups missing datapoint 'availability'

### ISSUE THREAD

**Issue by FrazerDungeon** [arteck/ioBroker.zigbee2mqtt#357]
### Link

https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#performance-considerations

### Adapter version

2.13.9

### What is missing or not working

I would like to see the datapoint availability for z2m groups. They are served by z2m but not shown in IOBroker.
![iobroker_datapoints_groups](https://github.com/arteck/ioBroker.zigbee2mqtt/assets/83769742/64510793-7a1d-428d-9b01-1f707546bb38)
![mqtt_state_availability_group](https://github.com/arteck/ioBroker.zigbee2mqtt/assets/83769742/1aadfd1e-7e0d-483e-be4b-1a991010dad8)

Please check last chapter in link above for group availabiliy. And I have set the availability setting generally in configuration.yaml not on device level.

### Device exposes

```JSON
For a group I can't find a ieee
```

**Comment by FrazerDungeon** [comment]
Is here any kind of progress?

**Comment by arteck** [comment]
check new version

**Comment by FrazerDungeon** [comment]
Sorry for the delay. I was on vacation. I checked it and confirm that it is working as requested. I also checked with single bulbs turn on and off. All fine.
Thank you very much.
