### ISSUE TITLE
Add to beta repository

### ISSUE THREAD

**Issue by Z18Aplha** [arteck/ioBroker.zigbee2mqtt#37]
I don't know why, but this adapter is not listed in the beta repository. I searched for such an adapter a very long time. Would be a shame to not see it in the adapter page in ioBroker! :)

Thanks for this work!!

**Comment by nox309** [comment]
Hi,
for adapters an inclusion in the repos would already be requested, but not yet granted. So we still have to wait a bit.

**Comment by Z18Aplha** [comment]
Ah okay. I already doubted myself because I could not follow the instructions in the doku.

I installed the adapter with ```npm install iobroker.zigbee2mqtt```
what is the command to add an instance of it?

```iobroker add iobroker.zigbee2mqtt``` does not work

**Comment by nox309** [comment]
You can install the adapter via the expert settings directly as a link from GitHub. Then an instance is also created. If not, you can simply create a new instance via the plus in the adapter list.

**Comment by Z18Aplha** [comment]
Yes of course. I forgot the way to install directly from github.

The adapter is running but does not turn green. All devices are ```availability: false``` but are controllable. Should i open a new issue for that or can we solve the problem here?

**Comment by o0shojo0o** [comment]
Hi, 

The following Zigbee2MQTT configuration parameters are mandatory for the adapter to process the data.
```yaml
advanced:
     legacy_api: false
     legacy_availability_payload: false
     output: json
device_options:
     legacy: false
availability: true
```

**Comment by o0shojo0o** [comment]
To the actual issues https://github.com/ioBroker/ioBroker.repositories/pull/1976
If you have any further problems please open a new issue :)

**Comment by Z18Aplha** [comment]
Thank you @o0shojo0o!
It was only missing the ```availability: true```. I already disabled the legacy features (also recommended by z2m).
