### ISSUE TITLE
[Feature] Use friendly_name for the device instead of IEEE Address

### ISSUE THREAD

**Issue by Z18Aplha** [arteck/ioBroker.zigbee2mqtt#38]
# Current behavior
- zigbee devices appear in iobroker with their IEEE address and have their friendly name in the column name

# Requested behavior
- zigbee devices appear in iobroker with their friendly name (maybe IEEE address as name?)

# Why?
- at least in my configuration the names of my devices are ```room-identifier``` (for example: "livingroom-tableLight" or "livingroom-motion")
- with the requested behavior the devices would be better distinguishable and are already grouped in the data structure of iobroker
- my current setup (z2m, external mqtt broker, iobroker.mqtt adapter) already shows the devices with their friendly name

# Requirements
- nothing, because z2m already checks whether a friendly name is already given

## Misc
I don't know how much you guys have to do. I would like to help, but I've never developed an iobroker adapter. Maybe you have a small task (like this one?) which I can do? I recently tried to implement the functionality of this adapter by my own - it generally worked well but not at a "public-level" ;)

**Comment by o0shojo0o** [comment]
I deliberately chose IEEE address, because I and also some testers come from the ioBroker.Zigbee adapters and it is the same there.
Many testers have more than 70 devices and would have to rebuild everything. 

also from programmers point of view I find no nice solution to use the friendly name because there much would have to be intercepted, because there many characters are allowed what is not allowed in ioBroker as state.

**Comment by o0shojo0o** [comment]
Rooms and functions are also assigned in ioBroker via the enums:
![image](https://user-images.githubusercontent.com/19333515/197756305-c56cc409-e9ee-4302-8b6e-d7d0c5893aa5.png)

**Comment by Z18Aplha** [comment]
Okay, understand. Thank you for the detailed answer. Makes sense for me, especially the programmers point ;)

Yeah, the rooms and functions enum is new for me (discovered the advantages last week). Still searching for a best practice to use them (1. assign major functions to id trees, like you did "Licht" for the whole device, or 2. assign detailed functions like "light_dimmer" to the specific dimmer datapoint of the device). Maybe you have some advice?

**Comment by o0shojo0o** [comment]
> 2. assign detailed functions like "light_dimmer" to the specific dimmer datapoint of the device). Maybe you have some advice?

The roles of the datapoint are responsible for that, I tried to detect everything as good as possible automatically.
Here is some more info about the topic 
https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md
![image](https://user-images.githubusercontent.com/19333515/197811509-b4df431f-1ea5-4f48-8878-411bc5fe5825.png)
