### ISSUE TITLE
Status of devices not updated

### ISSUE THREAD

**Issue by baennjer** [arteck/ioBroker.zigbee2mqtt#383]
### What happened?

After a while all or in some cases most devices in "objects" are indicated as offline allthough they are online and working fine.  The datapoint "available"  is showing false allthough the timestamp in datapoint  "last_seen" is just some minutes old. Also in the M2Z GUI the devices are online.
In the schreen shots the devices IkeaDoor1, IkeaPlug1 and IkeaPlug2 are online and working but are showen as offline:
![image](https://github.com/user-attachments/assets/318b7226-6802-4e19-aa27-0645de535d92)
![image](https://github.com/user-attachments/assets/5de60cbb-57ae-4db8-951f-7a40926f4450)
![image](https://github.com/user-attachments/assets/86526672-fe47-40bb-b4ee-5236b0a852ce)
![image](https://github.com/user-attachments/assets/7142fe86-3208-4536-9d53-922ccee6c486)

### What did you expect to happen?

Devices should be marked as available.

### How to reproduce it (minimal and precise)

After restart of Z2M instance the 3 devices are online....
![image](https://github.com/user-attachments/assets/066926a2-328a-463d-9bbf-8fabde7e4ce9)

### Adapter version

2.13.10

### Adapter Config Log

<html>
<body>

zigbee2mqtt.0 | 2024-10-07 08:41:18.731 | warn | z2m: Failed to ping 'IkeaMeasPlug3' (attempt 1/1, ZCL command 0xyyyyyyyyyyyyy/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
-- | -- | -- | --
zigbee2mqtt.0 | 2024-10-07 08:40:00.168 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/IkeaPlug2', payload '{"last_seen":"2024-10-07T08:40:00+02:00","linkquality":102,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":33816580,"latest_version":33816613,"state":"available"}}'
zigbee2mqtt.0 | 2024-10-07 08:39:28.133 | warn | z2m: Failed to ping 'IkeaMeasPlug2' (attempt 1/1, ZCL command 0xyyyyyyyyyyyyyy2e/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
zigbee2mqtt.0 | 2024-10-07 08:39:04.907 | warn | z2m: Failed to ping 'IkeaMeasPlug1' (attempt 1/1, ZCL command 0xyyyyyyyyyyyyyyya/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
zigbee2mqtt.0 | 2024-10-07 08:35:54.797 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/IkeaPlug1', payload '{"last_seen":"2024-10-07T08:35:54+02:00","linkquality":105,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":33816580,"latest_version":33816613,"state":"available"}}'
zigbee2mqtt.0 | 2024-10-07 08:35:00.202 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/IkeaPlug2', payload '{"last_seen":"2024-10-07T08:35:00+02:00","linkquality":102,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":33816580,"latest_version":33816613,"state":"available"}}'

</body>
</html>

**Comment by arteck** [comment]
check the docu
https://github.com/arteck/ioBroker.zigbee2mqtt/blob/main/docs/DE/DE_faq.md

**Comment by baennjer** [comment]
> check the docu https://github.com/arteck/ioBroker.zigbee2mqtt/blob/main/docs/DE/DE_faq.md

My problem isn't listed in the FAQs.
The initial question is: Why does the IOB zigbee2mqtt Adapter can not subscribe to and read the topic "availability"  correctly allthough the status is propperly submitted in this topic to the MQTT broker?

**Comment by softwarecrash** [comment]
> > check the docu https://github.com/arteck/ioBroker.zigbee2mqtt/blob/main/docs/DE/DE_faq.md
> 
> My problem isn't listed in the FAQs. The initial question is: Why does the IOB zigbee2mqtt Adapter can not subscribe to and read the topic "availability" correctly allthough the status is propperly submitted in this topic to the MQTT broker?

have you checked that your config matches the example in the docs?

**Comment by baennjer** [comment]
Since the availability status is correctly published to Mosqitto I obtain the data directly from there to generate possible unavailability alarms and notifications.
