### ISSUE TITLE
Adapter interferes with iobroker's adapter list

### ISSUE THREAD

**Issue by JoergGiencke** [arteck/ioBroker.zigbee2mqtt#386]
### What happened?

A) The Adapter does not show up in iobroker's adapter list.

B) After manual installation of the adapter, the adapter list remains completely empty. Only a reduction to individual categories shows results again. However, the ‘Hardware’ category (zigbee2mqtt's category) remains empty. In the list view, the ‘Hardware’ category cannot be expanded, but all other categories can.
After manually uninstalling the adapter (iobroker del zigbee2mqtt), everything is back to normal.
I was able to reproduce the problem on two separate iobroker installations.
By the way: The adapter works perfectly. There is only the problem with the adapter list.

### Adapter version

2.13.10

### Adapter Config Log

No log available

**Comment by Hunduster** [comment]
+1

**Comment by SpezialAgent** [comment]
+1

**Comment by JoergGiencke** [comment]
A hint from the iobroker forum: If you switch the repository to beta, the problem is ‘solved’. I can also confirm this for two installations.

**Comment by parvaresh** [comment]
This is a very **big problem** because once this adapter is in the list, the entire list will not be shown.
For example, if you search for Zigbee, no adapters will be shown in the list.

**Comment by PaulEins** [comment]
me too.
ioBroker cant new install.
