### ISSUE TITLE
Möglicher Fehler in der Doku

### ISSUE THREAD

**Issue by RelaxedHome** [arteck/ioBroker.zigbee2mqtt#399]
### Link

-

### Adapter version

2.13.6

### What is missing or not working

Ich hoffe das ist richtig hier. Ich habe wie Hier beschrieben https://github.com/arteck/ioBroker.zigbee2mqtt/blob/main/docs/DE/DE_faq.md  die yaml bearbeitet.  Danch ließ sich Zigbee2MQTT nicht mehr startet. Dort steht das man unter anderem das eintragen soll:
output: json         -so ließ sich Z2M nicht mehr starten

Laut der Doku https://www.zigbee2mqtt.io/guide/configuration/mqtt.html#mqtt-behaviour muss das so sein:
 
output: 'json'      -so konnte ich Zigbee2MQTT starten

### Device exposes

```JSON
-
```

**Comment by arteck** [comment]
danke habs korrigiert
