### ISSUE TITLE
Missing data for remotes (Müller Licht MLI-404011/MLI-404049)

### ISSUE THREAD

**Issue by copystring** [arteck/ioBroker.zigbee2mqtt#40]
Hey,

so I recently changed to using this adapter and noticed a weird behaviour where some data is missing from my tint remote.

Pressing a button on the remote makes it publish
`MQTT publish: topic 'zigbee2mqtt/FernbedienungHobbyraum', payload '{"action":"color_temperature_move","action_color_temperature":153,"action_color_temperature_direction":"up","action_transition_time":10,"last_seen":"2022-10-27T21:26:53+02:00","linkquality":65}'`
however not all of that data is going into the adapter. The data points for the adapter look like this:

![image](https://user-images.githubusercontent.com/1298861/198381475-abbd146c-f025-43ae-bbab-ac6d97165eba.png)

missing things like the value of action_color_temperature etc.
For other devices, smart plugs, RGB lights etc the data is fine. Just not for remotes. Same behaviour is happening for IKEA remotes

**Comment by o0shojo0o** [comment]
Can you please provide me with the link to your device? 
You can get it by clicking here:
![image](https://user-images.githubusercontent.com/19333515/198383608-cfc54353-056e-4746-8d3f-de4fe8c7a265.png)

**Comment by copystring** [comment]
Sure.
This is happening for the following the devices:
- https://www.zigbee2mqtt.io/devices/E1524_E1810.html#ikea-e1524%252Fe1810
- https://www.zigbee2mqtt.io/devices/E1812.html#ikea-e1812
- https://www.zigbee2mqtt.io/devices/MLI-404011_MLI-404049.html#m%25C3%25BCller%2520licht-mli-404011%252Fmli-404049

**Comment by o0shojo0o** [comment]
As here, for example, everything was created correctly on the basis of the exposes: https://www.zigbee2mqtt.io/devices/MLI-404011_MLI-404049.html#exposes
What did you expect?

**Comment by o0shojo0o** [comment]
Stop now I see it!

**Comment by o0shojo0o** [comment]
Can you please install the latest git version and put in the datapoint `zigbee2mqtt.0.info.debugmessages` the ieee address `0x2c1165fffe2cae93` and give me the result from the warning log which starts like this:
 `-->> fromZ2M -> 0x2c1165fffe2cae93 exposes:`

**Comment by copystring** [comment]
Sure.

`2022-10-28 07:37:03.049 - warn: zigbee2mqtt.0 (7285) --->>> fromZ2M -> 0x2c1165fffe2cae93 exposes: {"date_code":"","definition":{"description":"Tint remote control","exposes":[{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["on","off","toggle","brightness_down_click","brightness_up_click","color_temp","color_wheel","brightness_0_release","brightness_1_release","brightness_0_hold","brightness_1_hold"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"MLI-404011/MLI-404049","options":[{"access":2,"description":"Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true).","name":"legacy","property":"legacy","type":"binary","value_off":false,"value_on":true}],"supports_ota":false,"vendor":"Müller Licht"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genPowerCfg","genIdentify","genGroups","touchlink","manuSpecificTuya","genBasic"],"output":["genOta","genTime","genBasic","genIdentify","genGroups","genScenes","genOnOff","genLevelCtrl","touchlink","57347"]},"configured_reportings":[],"scenes":[]}},"friendly_name":"FernbedienungHobbyraum","ieee_address":"0x2c1165fffe2cae93","interview_completed":true,"interviewing":false,"manufacturer":"_TZ3000_bdbb0fon","model_id":"TS1001","network_address":5985,"power_source":"Battery","supported":true,"type":"EndDevice"}`

**Comment by o0shojo0o** [comment]
I was afraid that the exposes do not contain the information that these actions contain numerical values.
With my adapter, 99% of all data points are generated dynamically based on the exposes, so that no devices have to be mapped.
Now I have to think about how to get a handle on this.
```json
        "exposes": [
            {
                "access": 1,
                "description": "Triggered action (e.g. a button click)",
                "name": "action",
                "property": "action",
                "type": "enum",
                "values": [
                    "on",
                    "off",
                    "toggle",
                    "brightness_down_click",
                    "brightness_up_click",
                    "color_temp",
                    "color_wheel",
                    "brightness_0_release",
                    "brightness_1_release",
                    "brightness_0_hold",
                    "brightness_1_hold"
                ]
            },
            {
                "access": 1,
                "description": "Link quality (signal strength)",
                "name": "linkquality",
                "property": "linkquality",
                "type": "numeric",
                "unit": "lqi",
                "value_max": 255,
                "value_min": 0
            }
        ],        
```
What I would still be interested in is how is this mapped in Zibee2MQTT? 
So here:  
![image](https://user-images.githubusercontent.com/19333515/198549477-3bf98be6-98be-4f15-97be-1fc7a88c47e0.png)

**Comment by o0shojo0o** [comment]
Did you ever have time to talk in Discord?

**Comment by copystring** [comment]
Sure. This evening at about 9:30?

**Comment by o0shojo0o** [comment]
> Sure. This evening at about 9:30?

I'm on the road tonight and unfortunately do not know if I'm already back home then

I have but times a shot in the dark dared, you like to install the Dev branch and test how it behaves?   
https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/dev_MLI-404011_MLI-404049

**Comment by copystring** [comment]
I'll try out this evening.

**Comment by copystring** [comment]
Okay. I tested the version you linked.
Deleted the data points for the remote and restarted the adapter.
Now it looks like this: 
![image](https://user-images.githubusercontent.com/1298861/198711073-60c1e83e-fb26-4207-b343-54063f80da44.png)

Color always stays 0 and colortemp always null.

Pressing the color wheel shows this in the log: `--->>> fromZ2M -> 0x2c1165fffe2cae93 states: {"payload":{"action":"color_move","action_color":{"x":0.598,"y":0.39},"action_transition_time":0,"last_seen":"2022-10-28T20:53:50+02:00","linkquality":72},"topic":"FernbedienungHobbyraum"}`

Pressing the color temp shows this: `--->>> fromZ2M -> 0x2c1165fffe2cae93 states: {"payload":{"action":"color_temperature_move","action_color_temperature":153,"action_color_temperature_direction":"up","action_transition_time":10,"last_seen":"2022-10-28T20:54:39+02:00","linkquality":69},"topic":"FernbedienungHobbyraum"}`

Brightness is the same as before. Showing true instead of the actual brightness sent by the remote:
`--->>> fromZ2M -> 0x2c1165fffe2cae93 states: {"payload":{"action":"brightness_step_up","action_step_size":43,"action_transition_time":0.1,"last_seen":"2022-10-28T20:55:26+02:00","linkquality":69},"topic":"FernbedienungHobbyraum"}`


This is what it looks like on the webinterface of z2m:
![image](https://user-images.githubusercontent.com/1298861/198711901-1e77e15e-5a35-4464-8042-73a9053a7836.png)
![image](https://user-images.githubusercontent.com/1298861/198711950-9641d217-9728-4e2f-be68-ad532db144a8.png)
![image](https://user-images.githubusercontent.com/1298861/198712008-118ca473-d16e-4867-96b7-3d895d8b7062.png)

**Comment by copystring** [comment]
Fixed with https://github.com/Koenkk/zigbee-herdsman-converters/pull/4850 waiting for the merge.
