### ISSUE TITLE
please change the log level for simple loggings: z2m:mqtt: MQTT publish: topic

### ISSUE THREAD

**Issue by Schmakus** [arteck/ioBroker.zigbee2mqtt#405]
### What happened?

on every publish you write an info log

### What did you expect to happen?

change it to debug log and show only warnings and errors

### Adapter version

v2.13.6

### Adapter Config Log

...

### Log

zigbee2mqtt.0 | 2024-11-27 18:09:59.382 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Wohnzimmer_Spot_04', payload '{"last_seen":"2024-11-27T18:09:59+01:00","linkquality":0}'
-- | -- | -- | --
zigbee2mqtt.0 | 2024-11-27 18:09:58.785 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro_Spot_2', payload '{"last_seen":"2024-11-27T18:09:58+01:00","linkquality":10}'
zigbee2mqtt.0 | 2024-11-27 18:09:59.433 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro_Spot_3', payload '{"last_seen":"2024-11-27T18:09:59+01:00","linkquality":21}'
zigbee2mqtt.0 | 2024-11-27 18:09:59.382 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Wohnzimmer_Spot_04', payload '{"last_seen":"2024-11-27T18:09:59+01:00","linkquality":0}'
zigbee2mqtt.0 | 2024-11-27 18:09:58.785 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro_Spot_2', payload '{"last_seen":"2024-11-27T18:09:58+01:00","linkquality":10}'
zigbee2mqtt.0 | 2024-11-27 18:09:58.330 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Küche_Spot_3', payload '{"last_seen":"2024-11-27T18:09:58+01:00","linkquality":14}'
zigbee2mqtt.0 | 2024-11-27 18:09:57.018 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Büro_Spot_5', payload '{"last_seen":"2024-11-27T18:09:57+01:00","linkquality":80}'
zigbee2mqtt.0 | 2024-11-27 18:09:56.231 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Küche_Spot_4', payload '{"last_seen":"2024-11-27T18:09:56+01:00","linkquality":14}'
zigbee2mqtt.0 | 2024-11-27 18:09:54.136 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Küche_Spot_6', payload '{"last_seen":"2024-11-27T18:09:54+01:00","linkquality":14}'
zigbee2mqtt.0 | 2024-11-27 18:09:52.045 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Küche_Spot_5', payload '{"last_seen":"2024-11-27T18:09:52+01:00","linkquality":14}'
zigbee2mqtt.0 | 2024-11-27 18:09:49.931 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Küche_Spot_8', payload '{"last_seen":"2024-11-27T18:09:49+01:00","linkquality":18}'
zigbee2mqtt.0 | 2024-11-27 18:09:47.819 | info | z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Esszimmer_Spot_3', payload '{"last_seen":"2024-11-27T18:09:47+01:00","linkquality":18}'

**Comment by arteck** [comment]
this is directly from z2m.. you can disable it in settings

![grafik](https://github.com/user-attachments/assets/e2ac769f-173d-475b-81cd-de7b55beb656)
