### ISSUE TITLE
Im IOB über Objkete nicht zu steuern 

### ISSUE THREAD

**Issue by h2okopfmt** [arteck/ioBroker.zigbee2mqtt#48]
**Describe the bug**  
LED Treiber Hersteller
[Gledopto](https://www.zigbee2mqtt.io/supported-devices/#v=Gledopto)
Modell
[GL-C-007-2ID](https://www.zigbee2mqtt.io/devices/GL-C-007-2ID.html#gledopto-gl-c-007-2id)
Lässt sich über Kachel streuen aber die Ojektete nicht.
Adapter gerade updated rübergezogen .

**To Reproduce**  
wie oben beschrieben.
über Kachel lässt sich Lampe steuern obere Objekte nicht

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
aktuell 2.11.22 14:00 Uhr

 - Adapter version: aktuell 2.11.22 14:00 Uhr 2.3.0
 - JS-Controller version: 4.0.23
 - Node version: Node.js: v16.17.1
 - Operating system: Docker auf dem PI 4 8gb

**Additional context**  

IEEE Addresse 0x00124b0019c77d42
Im Log ist nix drin weder mit der IEEE Nummer noch anders gefiltert wenn ich über Ojkete was steuern möchte.

Das kommt wenn ich über Kachel steuer.
<img width="1510" alt="Bildschirmfoto 2022-11-02 um 15 48 18" src="https://user-images.githubusercontent.com/45139677/199521338-fdc87b75-a190-4847-bc80-a664f6be449c.png">

<img width="363" alt="Bildschirmfoto 2022-11-02 um 14 01 10" src="https://user-images.githubusercontent.com/45139677/199497232-f907ed4f-06b4-4090-a186-0400ff1a9501.png">
<img width="1385" alt="Bildschirmfoto 2022-11-02 um 14 00 54" src="https://user-images.githubusercontent.com/45139677/199497249-27db0740-775c-40f2-8f9b-c0ed9ee9df08.png">

**Comment by nox309** [comment]
I already anticipate, please enter the IEEE address, i.e. 0x0012... Enter in the debug messages and then post the log here.

For me it looks first time correctly and/or the reason values would be correctly stored.

Ich greife schon Mal vor, bitte die IEEE Adresse, also 0x0012... In die debug Nachrichten eintragen und das log dann hier Posten.

Für mich sieht es erst Mal richtig aus bzw. Die Grund Werte würden richtig abgelegt.

**Comment by o0shojo0o** [comment]
@h2okopfmt ich bräuchte noch die [Logausgabe von den Exposes](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/blob/main/docs/EN/EN_faq.md#how-do-i-get-the-exposes-from-a-device-) um hier jetzt weiter zu machen.

**Comment by o0shojo0o** [comment]
Ok, bitte teste den `dev_#48` Branche (https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/dev_%2348)
