### ISSUE TITLE
[Device problem]: Sonoff ZBMINI-L

### ISSUE THREAD

**Issue by Evil95** [arteck/ioBroker.zigbee2mqtt#54]
### Link

https://www.zigbee2mqtt.io/devices/zbmini-l.html

### Adapter version

2.3.0

### What is missing or not working

Datapoint "state" do not update, after light switch is pressed or alexa is used to turn the light on. It only updates if i change the state directly in iobroker by myself. 
**P.S.: Ignore the available is shown offline. I've not changed the configuration.yaml yet. Even if i change it, the problem is still present.**
![zbminil](https://user-images.githubusercontent.com/45834434/200053808-04311f89-ea31-489f-a925-3658b5cc63ff.png)

PPS: This happend to every device. Even Plugs do not update their states. 

### Device exposes

```JSON
zigbee2mqtt.0
	2022-11-04 19:59:42.332	warn	--->>> fromZ2M -> 0x00124b0026b7fd2e states: {"payload":{"last_seen":"2022-11-04T19:58:47+01:00","linkquality":109,"state":"ON","update":{"state":"idle"}},"topic":"Licht_Arbeitszimmer"}
zigbee2mqtt.0
	2022-11-04 19:59:42.331	warn	--->>> fromZ2M -> 0x00124b0026b7fd2e states: {"payload":{"last_seen":"2022-11-04T19:58:47+01:00","linkquality":109,"state":"ON","update":{"state":"idle"}},"topic":"Licht_Arbeitszimmer"}
zigbee2mqtt.0
	2022-11-04 19:59:35.812	warn	--->>> fromZ2M -> 0x00124b0026b7fd2e states: {"payload":{"last_seen":"2022-11-04T19:58:47+01:00","linkquality":109,"state":"ON","update":{"state":"idle"}},"topic":"Licht_Arbeitszimmer"}
zigbee2mqtt.0
	2022-11-04 19:59:35.786	warn	--->>> fromZ2M -> 0x00124b0026b7fd2e exposes: {"date_code":"20220507","definition":{"description":"Zigbee smart switch (no neutral)","exposes":[{"features":[{"access":7,"description":"On/off state of the switch","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":7,"description":"Controls the behavior when the device is powered on","name":"power_on_behavior","property":"power_on_behavior","type":"enum","values":["off","previous","on"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"ZBMINI-L","options":[],"supports_ota":true,"vendor":"SONOFF"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genIdentify","genGroups","genScenes","genOnOff","genOnOffSwitchCfg","64599","64672"],"output":["genOta"]},"configured_reportings":[],"scenes":[]}},"friendly_name":"Licht_Arbeitszimmer","ieee_address":"0x00124b0026b7fd2e","interview_completed":true,"interviewing":false,"manufacturer":"SONOFF","model_id":"ZBMINI-L","network_address":12204,"power_source":"Mains (single phase)","software_build_id":"1.1.1","supported":true,"type":"EndDevice"}
```

**Comment by nox309** [comment]
Just a question, but in your screenshot it looks like the devices are all offline, did you check that?
If this is the case (from Adapater's point of view) it is clear why the states do not update.

**Comment by Evil95** [comment]
I kindly repeat: Ignore the available is shown offline. I've not changed the configuration.yaml yet. Even if i change it, the problem is still present.

**Comment by o0shojo0o** [comment]
Can you please make the state object available to me? 
The one when you press the pencil.
![image](https://user-images.githubusercontent.com/19333515/200077774-375b9443-2853-4a71-b1ff-a6d01852a32b.png)

**Comment by Evil95** [comment]
Yes.
![Screenshot 2022-11-04 224946](https://user-images.githubusercontent.com/45834434/200080206-a7604f71-eafd-4970-be80-f16d4690cf84.png)
![Screenshot 2022-11-04 225001](https://user-images.githubusercontent.com/45834434/200080208-1317b729-835d-4c5b-93b3-387748854b4f.png)

**Comment by o0shojo0o** [comment]
That's all ok, I can't recreate the error with the current git version.

**Comment by Evil95** [comment]
> info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/state', payload 'OFF'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/last_seen', payload '2022-11-04T22:57:40+01:00'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/linkquality', payload '65'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/state', payload 'ON'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/update-state', payload 'idle'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/last_seen', payload '2022-11-04T22:57:40+01:00'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/linkquality', payload '65'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/update-state', payload 'idle'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/state', payload 'ON'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/last_seen', payload '2022-11-04T22:57:40+01:00'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/linkquality', payload '65'
info 2022-11-04 22:57:40MQTT publish: topic 'zigbee2mqtt/Licht_Arbeitszimmer/update-state', payload 'idle'

Hier mal ein Auzug aus dem Zigbee2MQTT Log sobald ich per Alexa/Lichtschalter den ZBMini-L anschalte. Sieht eigentlich gut aus.
Vielleicht habe ich im Adapter was falsch eingestellt? So sehen meine Einstellungen aus.
![Screenshot 2022-11-04 230047](https://user-images.githubusercontent.com/45834434/200081407-47271577-7194-480b-bbe5-09428af50503.png)

**Comment by o0shojo0o** [comment]
Sieht auch alles ok  aus,  aber wenn ich das richtig sehe hast du noch den legacy Mode für das Device an?

So solle es in der Conf stehen 
```
 advanced:
...
     legacy_api: false
     legacy_availability_payload: false
...
 device_options:
     legacy: false
````

**Comment by Evil95** [comment]
Ist alles so eingestellt. "legacy_availability_payload: false" ist bei mir aktuell ausgeklammert, weil sonst meine Skripte und VIS verrückt spielen. Selbst wenn ich die Raute entferne und die Option somit aktviere, bleibt das Problem bestehen.

![Screenshot 2022-11-04 232412](https://user-images.githubusercontent.com/45834434/200083575-2e9f131d-92eb-40c4-9d1a-f9002dc17628.png)

**Comment by o0shojo0o** [comment]
Kannst du mal prüfen ob vielleicht versehentlich für dieses Device aktiviert ist? 
![image](https://user-images.githubusercontent.com/19333515/200084489-31040331-b705-4d14-9744-49c96ad599ab.png)
Ich kann mir das echt nicht erklären :(

**Comment by Evil95** [comment]
Diese Option bietet er mir gar nicht an. Aber das Problem habe ich ja nicht nur bei den ZBMini's, sondern auch bei Steckdosen. 
Keine Ahnung warum der Adapter bei mir nicht so richtig möchte. :/

![Screenshot 2022-11-04 233948](https://user-images.githubusercontent.com/45834434/200085056-92742830-8183-4882-a016-2ee1f439500a.png)

**Comment by o0shojo0o** [comment]
Ich gehe von aus das der Adapter sonst an war oder? 

![image](https://user-images.githubusercontent.com/19333515/200091339-16b68a80-8c7c-46b9-a799-2ef449710f62.png)

**Comment by Evil95** [comment]
Ja natürlich.

**Comment by o0shojo0o** [comment]
> Ja natürlich.

Hatte ich auch mit gerechtet, aber wollte dennoch frag ;)  
Du hast wahrscheinlich auch nach der Änderung in der  Konfiguration z2m neu gestartet.
Mir gehen echt die Ideen aus.. 

Und das Problem ist nur bei den Device? 

Wann hast Du zuletzt aus dem Git installiert ?

**Comment by Evil95** [comment]
Ja Z2M habe ich nach jeder Änderung der config yaml neu gestartet.

Das Problem tritt bei alles Devices auf, welche sich schalten lassen, also auch Steckdosen zum Beispiel.

Vor ca 3 Tagen hatte ich den Adapter per npm installiert. Und zwar die Version 2.3.0. 
Benutzt habe ich folgenden Befehl:
npm install iobroker.zigbee2mqtt@2.3.

**Comment by o0shojo0o** [comment]
Installier mal bitte über die Git Katze 
Mir der URL -> https://github.com/o0shojo0o/ioBroker.zigbee2mqtt
![image](https://user-images.githubusercontent.com/19333515/200125355-8fe05769-db6d-4c24-9adf-31ee1820ec6d.png)

**Comment by Evil95** [comment]
Alles klar. Probiere ich gleich morgen früh, sobald ich zuhause bin. :)

**Comment by Evil95** [comment]
Hat leider auch nichts gebracht. 
Schalten per iobroker funktioniert, aber sobald man den Schalter physisch betätigt, wird die Änderung nicht an den Adapter weiter gereicht. Im MQTT-Server kommt sie aber an. 

![Screenshot_20221106_082932_Firefox.jpg](https://user-images.githubusercontent.com/45834434/200159346-cb9d2991-f985-4b13-b69f-68a49793864f.jpg)

**Comment by o0shojo0o** [comment]
Sorry, ich kann mir keinen Reim darauf machen, warum das es bei dir nicht laufen will.

**Comment by Evil95** [comment]
Ich würde ja gerne anstatt WebSockt, einfach Externer MQTT-Broker testen, aber leider bekomme ich dann immer die Fehlermeldung "Client [ioBroker.zigbee2mqtt_a957fa] has invalid password(undefined) or username(undefined)".
Was auch logisch ist, weil ich keinerlei Login-Daten hinterlegen kann.
![Unbenannt](https://user-images.githubusercontent.com/45834434/200368038-4fd7dbd1-6401-4871-a6eb-af076b20a80d.png)

**Comment by o0shojo0o** [comment]
Ja weil ich noch keine Zeit dafür hatte, und auch ungetestet ist. 
Es steht auch noch nicht fest ob die Option drinnen bleiben wird.

**Comment by Evil95** [comment]
Achso verstehe. Gut dann schließe ich dieses Issue erst einmal.

**Comment by Evil95** [comment]
Habe mittlerweile die Lösung gefunden. Es ist nötig, dass unter Einstellungen -> Erweitert -> "MQTT output type" auf json oder attribute_and_json steht. Dann klappt auch alles.

**Comment by Evil95** [comment]
Habe mittlerweile die Lösung gefunden. Es ist wichtig, dass unter Einstellungen -> Erweitert -> "MQTT Output Type" auf attribute_and_json oder json steht. Dies sollte es auch im Standardfall tun.

**Comment by o0shojo0o** [comment]
Das steht auch so in der Doku ;) 
![image](https://user-images.githubusercontent.com/19333515/202206615-5eecc56b-c06a-454c-b0bd-8db08f9decfa.png)

**Comment by o0shojo0o** [comment]
Oder auch hier -> [FAQ](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/blob/main/docs/DE/DE_faq.md#welche-zigbee2mqtt-konfigurationsparameter-werden-ben%C3%B6tigt-)
