### ISSUE TITLE
Keine Verbindung zum MQTT Server möglich

### ISSUE THREAD

**Issue by Caroma97** [arteck/ioBroker.zigbee2mqtt#66]
### What happened?

Hallo zusammen,

der Adapter kann sich bei mir mit keinem externen MQTT Server verbinden, weder über Websockets, noch dem Standard MQTT Protokoll. Andere Rechner im Netzt haben hier keinerlei Probleme. Auch eine Verbindung mit dem MQTT Broker Adapter in IoBroker selbst ist leider nicht möglich. 
Nur mit dem internen MQTT Server tritt das Problem nicht auf. Hier werden alle Geräte problemlos geladen und angezeigt.

Mein Setup:
IoBroker auf einem Ubuntu 21.04 Server
Node.js v16.18.1
npm 8.19.2
js controller 4.0.24
z2m Adapter 2.4.0

PS: Eine Implementierung für eine Authentifizierung beim Anmelden am MQTT Server würde ich sehr befürworten. Wir wollen doch alle keine offenen Server bei uns im Netz stehen lassen :)

### What did you expect to happen?

Adapter sollte sich mit einem externen MQTT Server verbinden können

### How to reproduce it (minimal and precise)

Adapter mit den Einstellungen für einen extenen MQTT Server  starten.

### Adapter version

2.4.0

### Log

<html>
<body>

zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.239 | info | Connect to Zigbee2MQTT over websocket connection.
-- | -- | -- | -- | --
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.090 | info | ==================================================================================
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.090 | info | \|\| Use Kelvin: no
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.090 | info | \|\| Proxy Zigbee2MQTT Logs to ioBroker Logs: activated
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.089 | info | \|\| Zigbee2MQTT Debug Log: deactivated
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.089 | info | \|\| Zigbee2MQTT Websocket Dummy MQTT-Server: deactivated
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.089 | info | \|\| Zigbee2MQTT Websocket Port: 9001
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.088 | info | \|\| Zigbee2MQTT Websocket Server: 192.168.1.222
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.088 | info | \|\| Zigbee2MQTT Connection Type: ws
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.087 | info | \|\| Zigbee2MQTT Frontend Port: 8091
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.087 | info | \|\| Zigbee2MQTT Frontend Server: 192.168.1.222
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.086 | info | \|\| Zigbee2MQTT Frontend Scheme: http
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.085 | info | ================================= Adapter Config =================================
zigbee2mqtt.0 | 2509 | 2022-11-14 22:27:28.057 | info | starting. Version 2.4.0 (non-npm: o0shojo0o/ioBroker.zigbee2mqtt#742772475956451c614f239ac34f4993e6718e0f) in /opt/iobroker/node_modules/iobroker.zigbee2mqtt, node: v16.18.1, js-controller: 4.0.23
host.iobroker |   | 2022-11-14 22:27:26.013 | info | instance system.adapter.zigbee2mqtt.0 started with pid 2509
host.iobroker |   | 2022-11-14 22:27:25.653 | info | "system.adapter.zigbee2mqtt.0" enabled

</body>
</html>

**Comment by o0shojo0o** [comment]
Moin, die Websocket Verbindung muss zur Zigbee2MQTT Instanz aufgebaut werden und nicht zum MQTT Broker.

**Comment by Caroma97** [comment]
Achso. Oh mein Gott... 
Jetzt funktioniert es auch problemlos :D
Vielen dank für die schnelle Hilfe.
