### ISSUE TITLE
osram button mini

### ISSUE THREAD

**Issue by arteck** [arteck/ioBroker.zigbee2mqtt#68]
### Link

https://www.zigbee2mqtt.io/devices/AC0251100NJ_AC0251600NJ_AC0251700NJ.html#osram-ac0251100nj%252Fac0251600nj%252Fac0251700nj

### Adapter version

2.4.1

### What is missing or not working

here tho zigbee adapter states
![grafik](https://user-images.githubusercontent.com/6681528/202784240-4d500834-c7fd-4978-ac27-9dac2aae4de0.png)

here the z2m
![grafik](https://user-images.githubusercontent.com/6681528/202784306-b4fca339-4bad-439f-8244-a90d40627e08.png)

### Device exposes

```JSON
2022-11-18 20:09:55MQTT publish: topic 'zigbee2mqtt/button.waschkeller.pumpe', payload '{"action":"on","battery":100,"battery_low":false,"last_seen":"2022-11-18T20:09:57+01:00","linkquality":105,"voltage":3100}'
Info 2022-11-18 20:09:57MQTT publish: topic 'zigbee2mqtt/button.waschkeller.pumpe', payload '{"action":"brightness_move_to_level","action_level":254,"action_transition_time":0.1,"battery":100,"battery_low":false,"last_seen":"2022-11-18T20:09:58+01:00","linkquality":105,"voltage":3100}'
Info 2022-11-18 20:09:58MQTT publish: topic 'zigbee2mqtt/button.waschkeller.pumpe', payload '{"action":"color_temperature_move","action_color_temperature":370,"action_transition_time":10,"battery":100,"battery_low":false,"last_seen":"2022-11-18T20:09:59+01:00","linkquality":105,"voltage":3100}'
Info 2022-11-18 20:09:58MQTT publish: topic 'zigbee2mqtt/button.waschkeller.pumpe', payload '{"action":"off","battery":100,"battery_low":false,"last_seen":"2022-11-18T20:10:00+01:00","linkquality":105,"voltage":3100}'
```

link to device config
https://github.com/ioBroker/ioBroker.zigbee/blob/d834e8433e2e5b14ebe51e1e1241237014a8afbf/lib/devices.js#L987

ok think the problem is here
https://github.com/Koenkk/zigbee2mqtt/issues/13592

it works little differently as zigbee adapter
when you press the corcle (middle button) you can switch the enum. but this works not really

**Comment by o0shojo0o** [comment]
Can you share the payload of `move_to_saturation`, `hue_move` with me?

**Comment by arteck** [comment]
its same as on/off

**Comment by o0shojo0o** [comment]
`move_to_saturation` must have a `number` in the payload and not a `boolean`. 
`hue_move` if necessary also ...

I know that the states of the remote control are not optimal, but we want to at least properly integrate them ;)

**Comment by o0shojo0o** [comment]
![image](https://user-images.githubusercontent.com/19333515/202900514-105d2b18-0d8b-40c9-8571-e7469ff44695.png)
Thanks for the data, please test the dev branch: https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/dev_%2368
and let me know :)
