### ISSUE TITLE
[Device problem]: Texteingabe Zahlenfeld 

### ISSUE THREAD

**Issue by Ricox1975** [arteck/ioBroker.zigbee2mqtt#94]
### Link

https://www.zigbee2mqtt.io/devices/KEYZB-110.html

### Adapter version

2.4.5

### What is missing or not working

<img width="1485" alt="Bildschirm­foto 2022-12-25 um 08 33 29" src="https://user-images.githubusercontent.com/52467622/209460439-c4e2090c-df13-45d1-92d5-5e7a93eb8328.png">

<img width="1485" alt="Bildschirm­foto 2022-12-25 um 08 34 11" src="https://user-images.githubusercontent.com/52467622/209460470-ac6bae54-38ee-4013-9fb2-cae0a3e1e56c.png">

### Device exposes

```JSON
Zahlencode wird nicht übernommen
```

**Comment by o0shojo0o** [comment]
Hi @Ricox1975 
Ich brauche zwingend die Exposes um hier was fixen zu können.
Wie du die bekommst ist hier beschrieben:

https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/blob/main/docs/DE/DE_faq.md#wie-erhalte-ich-die-expositionsdaten-eines-ger%C3%A4ts-

**Comment by Ricox1975** [comment]
`--->>> fromZ2M -> 0x0015bc004300172b exposes: {"date_code":"2022-05-10 14:09","definition":{"description":"Keypad","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Indicates if the battery of this device is almost empty","name":"battery_low","property":"battery_low","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Voltage of the battery in millivolts","name":"voltage","property":"voltage","type":"numeric","unit":"mV"},{"access":1,"description":"Indicates whether the device is tampered","name":"tamper","property":"tamper","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Pin code introduced.","name":"action_code","property":"action_code","type":"text"},{"access":1,"description":"Last action transaction number.","name":"action_transaction","property":"action_transaction","type":"numeric"},{"access":1,"description":"Alarm zone. Default value 23","name":"action_zone","property":"action_zone","type":"text"},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["disarm","arm_day_zones","arm_night_zones","arm_all_zones","exit_delay","emergency"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"KEYZB-110","options":[],"supports_ota":true,"vendor":"Develco"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genScenes","genOnOff"],"output":[]},"configured_reportings":[],"scenes":[]},"44":{"bindings":[{"cluster":"genPollCtrl","target":{"endpoint":1,"ieee_address":"0x00124b0022811b60","type":"endpoint"}},{"cluster":"genPowerCfg","target":{"endpoint":1,"ieee_address":"0x00124b0022811b60","type":"endpoint"}},{"cluster":"ssIasZone","target":{"endpoint":1,"ieee_address":"0x00124b0022811b60","type":"endpoint"}},{"cluster":"ssIasAce","target":{"endpoint":1,"ieee_address":"0x00124b0022811b60","type":"endpoint"}},{"cluster":"genIdentify","target":{"endpoint":1,"ieee_address":"0x00124b0022811b60","type":"endpoint"}}],"clusters":{"input":["genBasic","genIdentify","genPollCtrl","ssIasZone","genPowerCfg"],"output":["genIdentify","genTime","ssIasAce","genOta"]},"configured_reportings":[{"attribute":"batteryVoltage","cluster":"genPowerCfg","maximum_report_interval":62000,"minimum_report_interval":3600,"reportable_change":0}],"scenes":[]}},"friendly_name":"___Key_0x0015bc004300172b","ieee_address":"0x0015bc004300172b","interview_completed":true,"interviewing":false,"manufacturer":"frient A/S","model_id":"KEPZB-110","network_address":26229,"power_source":"Battery","supported":true,"type":"EndDevice"}`

**Comment by o0shojo0o** [comment]
Moin @Ricox1975, 
Macht nur der Datenpunkt Probleme oder noch andere?

**Comment by o0shojo0o** [comment]
Bitte teste mal den Dev Branch (https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/dev_%2394)

**Comment by Ricox1975** [comment]
keine Änderung
die Datenpunkte  action_zone und action_transaction werden auch nicht übernommen
`--->>> fromZ2M -> 0x0015bc004300172b exposes: {"date_code":"2022-05-10 14:09","definition":{"description":"Keypad","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Indicates if the battery of this device is almost empty","name":"battery_low","property":"battery_low","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Voltage of the battery in millivolts","name":"voltage","property":"voltage","type":"numeric","unit":"mV"},{"access":1,"description":"Indicates whether the device is tampered","name":"tamper","property":"tamper","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Pin code introduced.","name":"action_code","property":"action_code","type":"text"},{"access":1,"description":"Last action transaction number.","name":"action_transaction","property":"action_transaction","type":"numeric"},{"access":1,"description":"Alarm zone. Default value 23","name":"action_zone","property":"action_zone","type":"text"},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["disarm","arm_day_zones","arm_night_zones","arm_all_zones","exit_delay","emergency"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"KEYZB-110","options":[],"supports_ota":true,"vendor":"Develco"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genScenes","genOnOff"],"output":[]},"configured_reportings":[],"scenes":[]},"44":{"bindings":[{"cluster":"genPollCtrl","target":{"endpoint":1,"ieee_address":"0x00124b0022811b60","type":"endpoint"}},{"cluster":"genPowerCfg","target":{"endpoint":1,"ieee_address":"0x00124b0022811b60","type":"endpoint"}},{"cluster":"ssIasZone","target":{"endpoint":1,"ieee_address":"0x00124b0022811b60","type":"endpoint"}},{"cluster":"ssIasAce","target":{"endpoint":1,"ieee_address":"0x00124b0022811b60","type":"endpoint"}},{"cluster":"genIdentify","target":{"endpoint":1,"ieee_address":"0x00124b0022811b60","type":"endpoint"}}],"clusters":{"input":["genBasic","genIdentify","genPollCtrl","ssIasZone","genPowerCfg"],"output":["genIdentify","genTime","ssIasAce","genOta"]},"configured_reportings":[{"attribute":"batteryVoltage","cluster":"genPowerCfg","maximum_report_interval":62000,"minimum_report_interval":3600,"reportable_change":0}],"scenes":[]}},"friendly_name":"___Key_0x0015bc004300172b","ieee_address":"0x0015bc004300172b","interview_completed":true,"interviewing":false,"manufacturer":"frient A/S","model_id":"KEPZB-110","network_address":26229,"power_source":"Battery","supported":true,"type":"EndDevice"}`

**Comment by o0shojo0o** [comment]
Bügel jetzt bitte nochmal drüber habe grade noch was in den Dev Branch (https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/dev_%2394) gepusht :)

**Comment by Ricox1975** [comment]
nur zum Verständnis: ich füge die (https://github.com/o0shojo0o/ioBroker.zigbee2mqtt.git) unter adapter benutzerdefiniert aus ?
<img width="1188" alt="Bildschirm­foto 2022-12-26 um 11 26 36" src="https://user-images.githubusercontent.com/52467622/209538370-8b1d77c4-b606-440f-96ad-d4bdc603030a.png">

**Comment by o0shojo0o** [comment]
Fast ;) 
Nutze den Link :) 
https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/tree/dev_%2394

**Comment by Ricox1975** [comment]
danke funktioniert jetzt und  wieder dazu gelernt 
<img width="1337" alt="Bildschirm­foto 2022-12-26 um 11 32 29" src="https://user-images.githubusercontent.com/52467622/209538871-67340dc2-35a1-45a2-b292-e342e446c2f8.png">

**Comment by Ricox1975** [comment]
wie kann man dich supporten?

**Comment by o0shojo0o** [comment]
> wie kann man dich supporten?

Wenn du möchtest  ist hier drunter ein Paypal Link drinnen.
![image](https://user-images.githubusercontent.com/19333515/209539817-31f2a25d-d5c3-4441-9a00-8dd65f01a506.png)

Ist aber kein muss, da durch deinen entdeckten Bug der Adapter wieder ein Stück besser geworden ist :)
